### ISSUE TITLE
Add this plugin to Packman

### ISSUE THREAD

**Issue by umireon** [occ-ai/obs-backgroundremoval#342]
Packman is where the unofficial OBS binary for OpenSUSE is hosted.

https://pmbs.links2linux.org/

- [ ] Register to Packman
- [ ] Create the definition

**Comment by royshil** [comment]
@umireon what's the status of this? anything i can help with?

**Comment by umireon** [comment]
I asked on the mailing list of Packman but I've got no response. I will ask the list again later.

**Comment by royshil** [comment]
let's get this off of milestone v1.1.0 and on to v1.1.1 then

**Comment by umireon** [comment]
#425 needs to be merged.

**Comment by umireon** [comment]
I have submitted the request to add our plugin to the repository again.
