### ISSUE TITLE
Can you store the skip check update settings into global.ini?

### ISSUE THREAD

**Issue by umireon** [occ-ai/obs-backgroundremoval#400]
I'm afraid that the plugin data directory is not writable on Windows.

https://github.com/umireon/obs-pokemon-sv-screen-builder/tree/main/src/update-checker

I reimplemented the update checker and I concluded that we can safely use global.ini on every platform.

What do you think? @royshil

**Comment by royshil** [comment]
yes that sounds good
as long as we can read&write to/from it...   it makes little difference.

**Comment by umireon** [comment]
We can also use obs_module_config_path

**Comment by royshil** [comment]
> We can also use obs_module_config_path

i think this is the better solution.

**Comment by umireon** [comment]
I suppose obs's config file interface (for ini files) is easier to handle than JSON.

**Comment by umireon** [comment]
Then we should wait for the next obs-studio release before fixing the configuration problem.
It wouldn't be too late!
