### ISSUE TITLE
Update Available - Ignores "disable update checks"

### ISSUE THREAD

**Issue by MattyFresh68** [occ-ai/obs-backgroundremoval#431]
**Describe the bug**
Checking the box should disable update checks, and subsequently, not show the "update available" window upon launching obs after selecting to not check for updates

As seen in the video I will be adding, checking the box to "disable update checks" and cleanly closing obs has zero effect. Subsequent launches of obs continues to have the window pop up. 

**To Reproduce**
Install background removal plugin(not the latest version). Launch obs. See if update available pops up. If it does, select the option to no longer check for updates. Cleanly close obs with "exit" button. relaunch

Steps above

**Expected behavior**

**Screenshots**

**Log and Crash Report**
https://obsproject.com/logs/j0S7kMPJByKJQHRc

Upload your OBS log file here (`Help`>`Log Files`>`Show Log Files`) to help us find cause of the problem.

If OBS is crashing, upload the crash report here as well (`Help`>`Crash Reports`>`Show Crash Reports`).

**Desktop (please complete the following information):**

 - OS: \[e.g. iOS\] - Windows 11 22h2
 - Browser: \[e.g. chrome, safari\] n/a
 - Plugin Version: \[e.g. 0.5.1\] 1.1.5
 - OBS Version: \[e.g. 28.02\] 29.1.3

**Additional context**

https://github.com/royshil/obs-backgroundremoval/assets/66339760/10361076-52cd-4a66-bfbc-7d8d26ba079a

**Comment by umireon** [comment]
This bug will be fixed after the next OBS release.
