### ISSUE TITLE
Rocm support

### ISSUE THREAD

**Issue by takov751** [occ-ai/obs-backgroundremoval#440]
**Is your feature request related to a problem? Please describe.**

radeon cards can not be used.

**Describe the solution you'd like**

I was wondering if you would plan to add rocm as omnxruntime_provider

**Comment by royshil** [comment]
I attempted to add the AMD rocm executor but wasn't successful.
Onnx runtime didn't release a major update too, which I was hoping for.
I can try again and see if I can get it to work this time...
Would be great for AMD systems, which I also have.
