### ISSUE TITLE
background removal  

### ISSUE THREAD

**Issue by LocoLosCollection** [occ-ai/obs-backgroundremoval#457]
I have it downloaded the background removal. when I'm in the filters area that has the adjustments such as Threshold, contourfilterpercentage ect I am moving the bar across and nothing is changing my background is still the same.  Did i download the wrong software? I have Windows Computer and these this is these are the ones I downloaded.  
[obs-backgroundremoval-1.1.6-windows-x64-Installer.exe](https://github.com/obs-ai/obs-backgroundremoval/releases/download/1.1.6/obs-backgroundremoval-1.1.6-windows-x64-Installer.exe)

[obs-backgroundremoval-1.1.6-windows-x64.zip](https://github.com/obs-ai/obs-backgroundremoval/releases/download/1.1.6/obs-backgroundremoval-1.1.6-windows-x64.zip)

Should I had only downloaded one of them. Once I download do where do I save it and how do i run it with OBS program?

**Comment by LocoLosCollection** [comment]
<img width="648" alt="image" src="https://github.com/obs-ai/obs-backgroundremoval/assets/145822804/88a31049-0b9d-4b34-8d8f-c9b1b30a9f4d">

**Comment by jathanasiou** [comment]
Your threshold is 0, you need to get it higher.

**Comment by royshil** [comment]
@LocoLosCollection the plugin was installed correctly since you can see it in the filters list as well as add it and see the settings.

your settings are likely the problem. You can try the defaults first, clikc the "Defaults" button to restore
like @jathanasiou says threshold needs to be above 0 - try just the middle point 0.5
you can even try without a threshold - untick "Enable Threshold" 

let us know how it looks

**Comment by jumanjaydazed** [comment]
I'm in the same boat /...Zip file...all the settings are available...I tried adjusting every setting from min to max....nothing changes

**Comment by umireon** [comment]
Please post here the log of OBS which can be obtained from the Help menu.

**Comment by jumanjaydazed** [comment]
[2023-10-04 18-38-03.txt](https://github.com/obs-ai/obs-backgroundremoval/files/12802699/2023-10-04.18-38-03.txt)

**Comment by umireon** [comment]
The log indicates that our plugin has some bug and it stops working due to this bug.

@royshil Our plugin fails to stackBlue because the source image of stackBlur is empty. Will you work on this bug or do you want me to investigate this bug?

**Comment by royshil** [comment]
@umireon  I can fix it it quickly and put up a PR, hang on

**Comment by royshil** [comment]
the actual bug is this
```
18:50:14.949: Unable to get model filename models/tcmonodepth_tcsmallnet_192x320.onnx from plugin.
```

**Comment by royshil** [comment]
please check out #458 
while it's not a complete fix - it does resolve the problem of the logs blowing up

we must figure out why the plugin can't find the models
i suspect the model files are not installed in the expected location

@umireon do we have a way in OBS to check both in the "per-user" folder (%appdata%/obs-studio) as well as the "system" folder (e.g. c:/Program Files/)?

**Comment by LocoLosCollection** [comment]
Hi so i did set all to default, untick "Enable Threshold" still not able to adjust. The bug that is mentioned above could or is that the reason it is not working correctly? 
![image](https://github.com/obs-ai/obs-backgroundremoval/assets/145822804/3a02859e-60c0-4fd4-a969-a6f42b7665cd)

**Comment by umireon** [comment]
@LocoLosCollection Can you post here the log of OBS?

**Comment by umireon** [comment]
@LocoLosCollection Your installation of our plugin is indeed broken.
Can you reinstall our plugin using exe installer?

**Comment by LocoLosCollection** [comment]
ok where can i find it? do you have the link please

**Comment by umireon** [comment]
https://github.com/obs-ai/obs-backgroundremoval/releases/download/1.1.6/obs-backgroundremoval-1.1.6-windows-x64-Installer.exe

**Comment by LocoLosCollection** [comment]
ty once i download it do i just open obs or do i copy the plugin and paste it somewhere in obs?

**Comment by umireon** [comment]
You don't need to copy anything anywhere. Just execute the installer and follow the instructions.

**Comment by umireon** [comment]
@royshil Can we close this issue as stalled?

**Comment by royshil** [comment]
closing as stalled
