### ISSUE TITLE
Provide CUDA-enabled binary on Windows

### ISSUE THREAD

**Issue by umireon** [occ-ai/obs-backgroundremoval#465]

**Comment by umireon** [comment]
We can publish the DirectML version and the CUDA version.

**Comment by royshil** [comment]
@umireon  do you want to take a stab at building with https://github.com/microsoft/onnxruntime/releases/download/v1.16.0/onnxruntime-win-x64-gpu-1.16.0.zip ? or i shuold try

**Comment by umireon** [comment]
I have no access to a Windows machine until next week so I cannot give it a try soon.

**Comment by royshil** [comment]
alright let me give it a try then

**Comment by royshil** [comment]
i've started to implement in `roy.build_with_win32_cuda_support`
