### ISSUE TITLE
Update AUR packages

### ISSUE THREAD

**Issue by jetexe** [occ-ai/obs-backgroundremoval#476]
AUR packages are outdated for several months 

The current maintainer is @ngoonee. Maybe they need some community help?

https://aur.archlinux.org/packages/obs-backgroundremoval
https://aur.archlinux.org/packages/obs-backgroundremoval-git

**Comment by ngoonee** [comment]
Yeah I haven't been using OBS for a while now, as everything where I am is back to physical. I'll test and do an update now, but I'm not actually keeping an eye on versions - would be happy to hand over maintainership or co-maintainership to anyone who uses this more often at the current moment.

**Comment by ngoonee** [comment]
I have disowned both.

**Comment by umireon** [comment]
I'm not a maintainer of obs-backgroundremoval?

**Comment by Technetium1** [comment]
@umireon highly recommended that you comment here to request ownership with context ASAP: https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/message/INMZ27JR2TQ3GEOSCI5HUZTOEKEAWCJU/

**Comment by umireon** [comment]
I don't know what I should do.

**Comment by Technetium1** [comment]
@umireon OH, I guess only TUs & requester can reply to that!! If the package is updated soon (even in a minor way) the request will likely be declined. Otherwise, keep a close eye on it if the request does go through.

@Bitals please consider adding @umireon as a co-maintainer!

**Comment by umireon** [comment]
Thank you!
