### ISSUE TITLE
OBS doesn´t open since I installed the plugin

### ISSUE THREAD

**Issue by caparros06** [occ-ai/obs-backgroundremoval#477]
**Describe the bug**

I´ve installed the plugin, then opened OBS and it doesn´t launch. Then I uninstalled plugin and reinstalled OBS. OBS launched normally. Then I installed again the plugin, and OBS doesn´t open again.

**To Reproduce**

 - OS: Windows 10
 - Browser: Chrome
 - Plugin Version: 1.1.7
 - OBS Version: 29.1.3

**Comment by royshil** [comment]
@caparros06 any sort of log would be valuable
also please note the location of OBS on your hard drive e.g. `c:\program files\` or `c:\program files (x86)\` - this is important

**Comment by caparros06** [comment]
Hi.

Now I run OBS as administrator and it works.
Do you still need the report?

**Comment by royshil** [comment]
@caparros06 really you shouldn't need to, but i'm guessing the plugin .DLLs were installed in Administrator so now you're only able to run as administrator to make it work

it's a decent workaround, but the solution would be to give user permissions to the .DLL files.
