### ISSUE TITLE
Winget!

### ISSUE THREAD

**Issue by MrHinsh** [occ-ai/obs-backgroundremoval#478]
It would be great if you could publish this on Winget so that its easy to install and update.

**Comment by royshil** [comment]
@MrHinsh can you plz research this a bit and provide information on how to implement? 🙏

**Comment by Technetium1** [comment]
@royshil it's not too bad:
- https://github.com/microsoft/winget-create#welcome-to-the-windows-package-manager-manifest-creator-repository
- https://github.com/microsoft/winget-pkgs#submitting-a-package

**Comment by umireon** [comment]
We have no time to implement winget packages but any help towards the winget packages would be appreciated! Thanks.

**Comment by MrHinsh** [comment]
I have submitted a PR for the that included an updated GitHub action to Auto publish a new version automatically.

https://github.com/occ-ai/obs-backgroundremoval/pull/500

However I am waiting for the first version to pass on https://github.com/microsoft/winget-pkgs/pull/131370

**Comment by MrHinsh** [comment]
This is blocked by https://github.com/occ-ai/obs-backgroundremoval/issues/499

**Comment by MrHinsh** [comment]
https://github.com/occ-ai/obs-backgroundremoval/pull/500

**Comment by MrHinsh** [comment]
@umireon, @royshil  Winget has been approved and I have added PR:https://github.com/occ-ai/obs-backgroundremoval/pull/500 to add a new action (I did not want to change your existing process) that triggers when you ship a new version and updates the Winget version automtically.

**Comment by umireon** [comment]
Released.
