### ISSUE TITLE
Download blocked by Browser Security

### ISSUE THREAD

**Issue by kaim-as** [occ-ai/obs-backgroundremoval#479]
I can't download the executable installer via Edge Chromium from https://obs-ai.github.io/obs-backgroundremoval/windows.
The download get's blocked by Microsoft oc company policy because the installer is treated as unsafe.

Please provide the bits as zip file with instructions how to update the pugin.

---
Finally, I was able to download the file using Chrome

**Comment by umireon** [comment]
I suppose you can send the installer with the description to Microsoft. We appreciate your efforts to resolve this problem!
