### ISSUE TITLE
Installation blocked by Microsoft or Company Policy

### ISSUE THREAD

**Issue by kaim-as** [occ-ai/obs-backgroundremoval#480]
Installation issue

The installer is not digitally signed, so Microsoft or our company policy blocks this file.

Could you please digitally sign the file(s) with a valid certificate?

**Comment by umireon** [comment]
Please support us financially to sign our installer!

**Comment by umireon** [comment]
If we get $500 support annually, we can sign our installer. Thank you for considering supporting us!
