### ISSUE TITLE
obs-backgroundremoval-1.1.7-macos-universal

### ISSUE THREAD

**Issue by johardy1956** [occ-ai/obs-backgroundremoval#481]
Hi

QUESTION : Why is there is NO Background colour option? How can I get this?

I can not get this obs-backgroundremoval-1.1.7-macos-universal to work.
MacBook Pro running OS Ventura 13.6 2.6 GHz 6-Core Intel Core i7
OBS 29.1.3
I download obs-backgroundremoval-1.1.7-macos-universal and run installation which says successful.
Restart computer
In OBS I Have video capture device using my mac camera. 
I select filters / background removal
There is NO Background colour option so i can not create a green screen so the background tool only works very badly
QUESTION : Why is there is NO Background colour option? How can I get this?

Many thanks
Jo

**Comment by umireon** [comment]
Post here the screenshot and the log of OBS. Thanks.

**Comment by johardy1956** [comment]
Hi Kaito

Many thanks for getting back to me. 
I have 3 screenshots to send you. I have tried .png, .jpg and .pdf and none seem to upload properly, see below. PLease clarify file type

The 3 screenshots will show  one with my macbook spec, showing NO Background colour option in the listopf Background removal parameters. 

OBS = 29.1.3
And remover tool = obs-backgroundremoval-1.1.7-macos-universal

Any info. on how to rectify this would be great

Many thanks
Jo

![Screenshot 2023-10-25 at 09 38 08](https://github.com/obs-ai/obs-backgroundremoval/assets/148908768/706b3466-0075-49ac-9ed3-4f29bd6c9e23)
![Screenshot 2023-10-25 at 09 38 39](https://github.com/obs-ai/obs-backgroundremoval/assets/148908768/d946a5b8-53ff-4000-a496-935ad50108bc)
![Screenshot 2023-10-25 at 09 38 49](https://github.com/obs-ai/obs-backgroundremoval/assets/148908768/12f51312-388e-4552-b15b-188e63025b7b)

**Comment by johardy1956** [comment]
Oh - seems the screenshot have uploaded ok

**Comment by umireon** [comment]
Also can you try to uncheck focal blur?

**Comment by johardy1956** [comment]
2023-10-25 12-33-35.txt
2023-10-24 20-19-42.txt
2023-10-25 09-37-06.txt

**Comment by johardy1956** [comment]
[2023-10-24 20-19-42.txt](https://github.com/obs-ai/obs-backgroundremoval/files/13165389/2023-10-24.20-19-42.txt)
[2023-10-25 09-37-06.txt](https://github.com/obs-ai/obs-backgroundremoval/files/13165390/2023-10-25.09-37-06.txt)
[2023-10-25 12-33-35.txt](https://github.com/obs-ai/obs-backgroundremoval/files/13165391/2023-10-25.12-33-35.txt)
[2023-10-25 12-38-36.txt](https://github.com/obs-ai/obs-backgroundremoval/files/13165392/2023-10-25.12-38-36.txt)

**Comment by johardy1956** [comment]
Here you go

**Comment by johardy1956** [comment]
Thanks Kaito

here are the logs and screenshots. I opened OBS, removed background effect, closed and reopened OBS, added background effect, unchecked blur and so on. Still no background colour option

[2023-10-26 09-53-00.txt](https://github.com/obs-ai/obs-backgroundremoval/files/13175231/2023-10-26.09-53-00.txt)
[2023-10-26 09-53-31.txt](https://github.com/obs-ai/obs-backgroundremoval/files/13175232/2023-10-26.09-53-31.txt)

<img width="1416" alt="Screenshot 2023-10-26 at 09 54 04" src="https://github.com/obs-ai/obs-backgroundremoval/assets/148908768/283f9253-9051-434a-a0ab-d758cc5bc5fd">
<img width="1316" alt="Screenshot 2023-10-26 at 09 54 12" src="https://github.com/obs-ai/obs-backgroundremoval/assets/148908768/8ac6e6aa-d8af-45db-8ef0-0e35804a6f42">
<img width="1479" alt="Screenshot 2023-10-26 at 09 54 31" src="https://github.com/obs-ai/obs-backgroundremoval/assets/148908768/fab0641c-4e82-4e5b-a3d4-40356e958640">
<img width="1339" alt="Screenshot 2023-10-26 at 09 54 44" src="https://github.com/obs-ai/obs-backgroundremoval/assets/148908768/4fbd74eb-c770-4f67-9403-273ba8cf287c">
<img width="1344" alt="Screenshot 2023-10-26 at 09 54 59" src="https://github.com/obs-ai/obs-backgroundremoval/assets/148908768/fa05a4c5-4774-4578-b8fa-f69529ef0cbc">

**Comment by umireon** [comment]
It works correctly. This plugin is not intended to add a green background but simply removes the background of the portrait.
If your expectation of this plugin is removing the background of your portrait, the background is already gone.
If it is adding a virtual green screen to your portrait, you can add a green color source behind the camera source.

**Comment by umireon** [comment]
You can put your arbitrary background image behind the camera source with our plugin and this should be the result that people (hopefully including you) expect.

**Comment by umireon** [comment]
We have the latest official tutorial video. This would help you much.
https://www.youtube.com/watch?v=veqNEsMqEE0

**Comment by johardy1956** [comment]
Many thanks Kaito, I will look wt your latest comments over the weekend. And thank you very much for the how to video
