### ISSUE TITLE
Module Unloads No Reason

### ISSUE THREAD

**Issue by quarinteen** [occ-ai/obs-backgroundremoval#484]
**I have a fresh install, and I tried both unzipping the package, and I tried to use the installer. Same results either way. The "Remove Background" option does not show in the video source filter list. In the logs it is loading then it gets unloaded without error. This is out of the log |  
07:17:57.301:   Loaded Modules: 
07:17:57.302: ==== Startup complete ===============================================
07:17:57.385: All scene data cleared
07:25:33.735: [obs-websocket] [obs_module_unload] Shutting down...
07:25:33.736: [obs-websocket] [obs_module_unload] Finished shutting down.
07:25:33.741: [obs-backgroundremoval] plugin unloaded**

**Fresh Install then unzip plugin**

**Expected behavior**

**Screenshots**

**Log and Crash Report**

Upload your OBS log file here (`Help`>`Log Files`>`Show Log Files`) to help us find cause of the problem.

If OBS is crashing, upload the crash report here as well (`Help`>`Crash Reports`>`Show Crash Reports`).

**Desktop (please complete the following information):**

 - OS: \[e.g. iOS\]
 - Browser: \[e.g. chrome, safari\]
 - Plugin Version: \[e.g. 0.5.1\]
 - OBS Version: \[e.g. 28.02\]

**Additional context**

**Comment by umireon** [comment]
Please post here the full log and the screenshot that indicates that our plugin is not loaded.

**Comment by royshil** [comment]
closing as stalled
