### ISSUE TITLE
Not working on Mac OBS 28.1.2

### ISSUE THREAD

**Issue by Sven74Muc** [occ-ai/obs-backgroundremoval#485]
I updated OBS to 28.1.2 (can not instal v 29) and then installed the plugin. Then I started OBS, added a Video Source, went to filter... and there is no "Background Removal" filter available. I have an Intel Macbook Pro. 

The plugin is visible in ~/Library/Application Support/obs-studio/plugins
I deleted the plugin and re-installed it... no change

**Comment by Sven74Muc** [comment]
Log
-----

21:56:45.701: [macOS] Permission for audio device access granted.
21:56:45.709: [macOS] Permission for video device access granted.
21:56:45.719: [macOS] Permission for accessibility granted.
21:56:45.739: [macOS] Permission for screen capture granted.
21:56:45.739: Rosetta translation used: false
21:56:45.740: Command Line Arguments: /Applications/OBS.app/Contents/MacOS/OBS
21:56:45.740: CPU Name: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
21:56:45.740: CPU Speed: 2300MHz
21:56:45.740: Physical Cores: 4, Logical Cores: 8
21:56:45.740: Physical Memory: 32768MB Total
21:56:45.740: OS Name: macOS
21:56:45.740: OS Version: Version 14.0 (Build 23A344)
21:56:45.740: Kernel Version: 23.0.0
21:56:45.741: hotkeys-cocoa: Using layout 'com.apple.keylayout.German'
21:56:45.741: Current Date/Time: 2023-11-04, 21:56:45
21:56:45.741: Browser Hardware Acceleration: true
21:56:45.741: Qt Version: 6.3.1 (runtime), 6.3.1 (compiled)
21:56:45.741: Portable mode: false
21:56:46.124: OBS 28.1.2 (mac)
21:56:46.124: ---------------------------------
21:56:46.127: ---------------------------------
21:56:46.127: audio settings reset:
21:56:46.127: 	samples per sec: 48000
21:56:46.127: 	speakers:        2
21:56:46.127: 	max buffering:   960 milliseconds
21:56:46.127: 	buffering type:  dynamically increasing
21:56:46.140: ---------------------------------
21:56:46.140: Initializing OpenGL...
21:56:46.201: Loading up OpenGL on adapter Intel Inc. Intel(R) Iris(TM) Plus Graphics OpenGL Engine
21:56:46.201: OpenGL loaded successfully, version 4.1 INTEL-22.1.27, shading language 4.10
21:56:46.649: ---------------------------------
21:56:46.649: video settings reset:
21:56:46.649: 	base resolution:   1920x1080
21:56:46.649: 	output resolution: 1280x720
21:56:46.649: 	downscale filter:  Bicubic
21:56:46.649: 	fps:               60/1
21:56:46.649: 	format:            NV12
21:56:46.649: 	YUV mode:          Rec. 709/Partial
21:56:46.650: NV12 texture support not available
21:56:46.650: P010 texture support not available
21:56:46.650: Audio monitoring device:
21:56:46.650: 	name: Default
21:56:46.650: 	id: default
21:56:46.650: ---------------------------------
21:56:46.683: No AJA devices found, skipping loading AJA UI plugin
21:56:46.683: Failed to initialize module 'aja-output-ui'
21:56:46.712: No AJA devices found, skipping loading AJA plugin
21:56:46.712: Failed to initialize module 'aja'
21:56:46.733: Failed to load 'en-US' text for module: 'decklink-captions'
21:56:46.745: Failed to load 'en-US' text for module: 'decklink-output-ui'
21:56:46.759: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
21:56:46.759: Failed to initialize module 'decklink'
21:56:47.570: [VideoToolbox encoder]: Adding VideoToolbox encoders
21:56:47.712: [obs-browser]: Version 2.18.7
21:56:47.712: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.61.23+g2fe5a76+chromium-103.0.5060.134 (compiled)
21:56:47.873: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.0.1 | RPC Version: 1)
21:56:47.873: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.3.1 | Qt version (run-time): 6.3.1
21:56:47.873: [obs-websocket] [obs_module_load] Linked ASIO Version: 101201
21:56:47.879: [obs-websocket] [obs_module_load] Module loaded.
21:56:47.969: [vlc-video]: VLC 3.0.16 Vetinari found, VLC video source enabled
21:56:48.003: <StreamDeck> Plugin version 5.5.1.1
21:56:48.021: os_dlopen(/Users/i547876/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval->/Users/i547876/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval): dlopen(/Users/i547876/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval, 0x0101): Library not loaded: @rpath/obs-frontend-api.dylib
21:56:48.021:   Referenced from: <3DBF8FFA-8F19-3F1D-ADF5-10F6E55931D6> /Users/i547876/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval
21:56:48.021:   Reason: tried: '/Applications/OBS.app/Contents/Frameworks/obs-frontend-api.dylib' (no such file), '/Applications/OBS.app/Contents/Frameworks/obs-frontend-api.dylib' (no such file), '/Applications/OBS.app/Contents/Frameworks/obs-frontend-api.dylib' (no such file), '/Applications/OBS.app/Contents/Frameworks/obs-frontend-api.dylib' (no such file), '/usr/lib/obs-frontend-api.dylib' (no such file, not in dyld cache)
21:56:48.021: 
21:56:48.021: Module '/Users/i547876/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval' not loaded
21:56:48.032: os_dlopen(/Library/Application Support/obs-studio/plugins/StreamDeckPlugin/data/StreamDeckPluginASIO1-12-1.plugin/Contents/MacOS/StreamDeckPluginASIO1-12-1->/Library/Application Support/obs-studio/plugins/StreamDeckPlugin/data/StreamDeckPluginASIO1-12-1.plugin/Contents/MacOS/StreamDeckPluginASIO1-12-1): dlopen(/Library/Application Support/obs-studio/plugins/StreamDeckPlugin/data/StreamDeckPluginASIO1-12-1.plugin/Contents/MacOS/StreamDeckPluginASIO1-12-1, 0x0101): tried: '/Library/Application Support/obs-studio/plugins/StreamDeckPlugin/data/StreamDeckPluginASIO1-12-1.plugin/Contents/MacOS/StreamDeckPluginASIO1-12-1' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Application Support/obs-studio/plugins/StreamDeckPlugin/data/StreamDeckPluginASIO1-12-1.plugin/Contents/MacOS/StreamDeckPluginASIO1-12-1' (no such file), '/Library/Application Support/obs-studio/plugins/StreamDeckPlugin/data/StreamDeckPluginASIO1-12-1.plugin/Contents/MacOS/StreamDeckPluginASIO1-12-1' (no such file)
21:56:48.032: 
21:56:48.032: <StreamDeck Wrap> Failed Load
21:56:48.032: Failed to initialize module 'StreamDeckPlugin.so'
21:56:48.042: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so->/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so, 0x0101): Library not loaded: @executable_path/../Frameworks/QtWidgets.framework/Versions/5/QtWidgets
21:56:48.042:   Referenced from: <5988A92D-E853-3766-B96D-F6F4555BF38A> /Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so
21:56:48.042:   Reason: tried: '/Applications/OBS.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets' (no such file), '/System/Library/Frameworks/QtWidgets.framework/Versions/5/QtWidgets' (no such file, not in dyld cache)
21:56:48.042: 
21:56:48.043: Module '/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so' not loaded
21:56:48.043: ---------------------------------
21:56:48.043:   Loaded Modules:
21:56:48.043:     StreamDeckPlugin
21:56:48.043:     vlc-video
21:56:48.043:     text-freetype2
21:56:48.043:     rtmp-services
21:56:48.043:     obs-x264
21:56:48.043:     obs-websocket
21:56:48.043:     obs-vst
21:56:48.043:     obs-transitions
21:56:48.043:     obs-outputs
21:56:48.043:     obs-filters
21:56:48.043:     obs-ffmpeg
21:56:48.043:     obs-browser
21:56:48.043:     mac-virtualcam
21:56:48.043:     mac-videotoolbox
21:56:48.043:     mac-syphon
21:56:48.043:     mac-capture
21:56:48.043:     mac-avcapture
21:56:48.043:     image-source
21:56:48.043:     frontend-tools
21:56:48.043:     decklink-output-ui
21:56:48.043:     decklink-captions
21:56:48.043:     coreaudio-encoder
21:56:48.043: ---------------------------------
21:56:48.043: ==== Startup complete ===============================================
21:56:48.114: All scene data cleared
21:56:48.114: ------------------------------------------------
21:56:48.213: <StreamDeck> [Server] Listening on '127.0.0.1:39726'.
21:56:48.411: coreaudio: Device 'Microsoft Teams Audio' [48000 Hz] initialized
21:56:48.411: [Loaded global audio device]: 'Desktop-Audio'
21:56:48.415: coreaudio: failed to find device uid: AppleUSBAudioEngine:TASCAM:US-4x4HR:no serial number:1,2, waiting for connection
21:56:48.416: [Loaded global audio device]: 'Mikrofon-/AUX-Audio'
21:56:48.416:     - filter: 'Rauschunterdrückung' (noise_suppress_filter_v2)
21:56:48.416:     - filter: 'Noise Gate' (noise_gate_filter)
21:56:48.500: Test Cam: Selected device 'FaceTime HD-Kamera (integriert)'
21:56:48.516: Test Cam: Using preset High
21:56:48.664: Video Capture Device 2: Selected device 'FaceTime HD-Kamera (integriert)'
21:56:48.664: Video Capture Device 2: Using preset 1280x720
21:56:48.962: Video Capture Studio: Selected device 'FaceTime HD-Kamera (integriert)'
21:56:48.962: Video Capture Studio: Using preset 1280x720
21:56:48.983: Switched to scene 'Speaker Studio'
21:56:48.983: ------------------------------------------------
21:56:48.983: Loaded scenes:
21:56:48.983: - scene 'Cam links':
21:56:48.983:     - source: 'Window Capture' (window_capture)
21:56:48.983:     - source: 'Video Capture Device 2' (av_capture_input)
21:56:48.983:     - source: 'Display Capture' (display_capture)
21:56:48.983: - scene 'Cam links (groß)':
21:56:48.983:     - source: 'Window Capture' (window_capture)
21:56:48.983:     - source: 'Video Capture Device 2' (av_capture_input)
21:56:48.983:     - source: 'Display Capture' (display_capture)
21:56:48.983: - scene 'Cam rechts':
21:56:48.983:     - source: 'Window Capture' (window_capture)
21:56:48.983:     - source: 'Video Capture Device 2' (av_capture_input)
21:56:48.983:     - source: 'Display Capture' (display_capture)
21:56:48.983: - scene 'Cam rechts (groß)':
21:56:48.983:     - source: 'Window Capture' (window_capture)
21:56:48.983:     - source: 'Video Capture Device 2' (av_capture_input)
21:56:48.983:     - source: 'Display Capture' (display_capture)
21:56:48.983: - scene 'Cam full':
21:56:48.983:     - source: 'Window Capture' (window_capture)
21:56:48.983:     - source: 'Video Capture Device 2' (av_capture_input)
21:56:48.983:     - source: 'Display Capture' (display_capture)
21:56:48.983: - scene 'Speaker Studio':
21:56:48.989:     - source: 'Studio' (image_source)
21:56:48.989:     - source: 'Video Capture Studio' (av_capture_input)
21:56:48.989:         - filter: 'Rauschunterdrückung' (noise_suppress_filter_v2)
21:56:48.989: - scene 'Test':
21:56:48.989:     - source: 'Test Cam' (av_capture_input_v2)
21:56:48.989: ------------------------------------------------
21:57:11.990: ==== Shutting down ==================================================
21:57:12.150: All scene data cleared
21:57:12.150: ------------------------------------------------
21:57:12.219: [obs-websocket] [obs_module_unload] Shutting down...
21:57:12.221: [obs-websocket] [obs_module_unload] Finished shutting down.
21:57:12.221: [Scripting] Total detached callbacks: 0
21:57:12.221: Freeing OBS context data
21:57:12.221: 1 views remain at shutdown
21:57:12.226: == Profiler Results =============================
21:57:12.226: run_program_init: 3752.38 ms
21:57:12.226:  ┣OBSApp::AppInit: 31.415 ms
21:57:12.226:  ┃ ┗OBSApp::InitLocale: 16.861 ms
21:57:12.226:  ┗OBSApp::OBSInit: 3371.14 ms
21:57:12.226:    ┣obs_startup: 1.642 ms
21:57:12.226:    ┗OBSBasic::OBSInit: 2984.1 ms
21:57:12.226:      ┣OBSBasic::InitBasicConfig: 0.382 ms
21:57:12.226:      ┣OBSBasic::ResetAudio: 0.14 ms
21:57:12.226:      ┣OBSBasic::ResetVideo: 523.098 ms
21:57:12.226:      ┣OBSBasic::InitOBSCallbacks: 0.005 ms
21:57:12.226:      ┣OBSBasic::InitHotkeys: 0.034 ms
21:57:12.226:      ┣obs_load_all_modules2: 1393.85 ms
21:57:12.226:      ┃ ┣obs_init_module(aja-output-ui): 0.172 ms
21:57:12.226:      ┃ ┣obs_init_module(aja): 0.176 ms
21:57:12.226:      ┃ ┣obs_init_module(coreaudio-encoder): 0.001 ms
21:57:12.226:      ┃ ┣obs_init_module(decklink-captions): 0.002 ms
21:57:12.226:      ┃ ┣obs_init_module(decklink-output-ui): 0 ms
21:57:12.226:      ┃ ┣obs_init_module(decklink): 0.129 ms
21:57:12.226:      ┃ ┣obs_init_module(frontend-tools): 5.176 ms
21:57:12.226:      ┃ ┣obs_init_module(image-source): 0.032 ms
21:57:12.226:      ┃ ┣obs_init_module(mac-avcapture): 399.928 ms
21:57:12.226:      ┃ ┣obs_init_module(mac-capture): 0.068 ms
21:57:12.226:      ┃ ┣obs_init_module(mac-syphon): 0.002 ms
21:57:12.226:      ┃ ┣obs_init_module(mac-videotoolbox): 293.467 ms
21:57:12.226:      ┃ ┣obs_init_module(mac-virtualcam): 0.012 ms
21:57:12.226:      ┃ ┣obs_init_module(obs-browser): 96.326 ms
21:57:12.226:      ┃ ┣obs_init_module(obs-ffmpeg): 0.138 ms
21:57:12.226:      ┃ ┣obs_init_module(obs-filters): 0.026 ms
21:57:12.226:      ┃ ┣obs_init_module(obs-outputs): 0.008 ms
21:57:12.226:      ┃ ┣obs_init_module(obs-transitions): 0.008 ms
21:57:12.226:      ┃ ┣obs_init_module(obs-vst): 0.003 ms
21:57:12.226:      ┃ ┣obs_init_module(obs-websocket): 5.388 ms
21:57:12.226:      ┃ ┣obs_init_module(obs-x264): 0.001 ms
21:57:12.226:      ┃ ┣obs_init_module(rtmp-services): 8.433 ms
21:57:12.226:      ┃ ┣obs_init_module(text-freetype2): 0.036 ms
21:57:12.226:      ┃ ┣obs_init_module(vlc-video): 18.365 ms
21:57:12.226:      ┃ ┣obs_init_module(StreamDeckPlugin): 26.782 ms
21:57:12.226:      ┃ ┗obs_init_module(StreamDeckPlugin.so): 0.183 ms
21:57:12.226:      ┣OBSBasic::ResetOutputs: 31.501 ms
21:57:12.226:      ┣OBSBasic::CreateHotkeys: 0.05 ms
21:57:12.226:      ┣OBSBasic::InitService: 1.685 ms
21:57:12.226:      ┣OBSBasic::InitPrimitives: 0.103 ms
21:57:12.226:      ┗OBSBasic::Load: 922.107 ms
21:57:12.226: obs_hotkey_thread(25 ms): min=0 ms, median=0 ms, max=0.027 ms, 99th percentile=0.003 ms, 100% below 25 ms
21:57:12.226: audio_thread(Audio): min=0.01 ms, median=0.051 ms, max=17.344 ms, 99th percentile=4.538 ms
21:57:12.226: obs_graphics_thread(16.6667 ms): min=0.085 ms, median=7.262 ms, max=565.193 ms, 99th percentile=31.34 ms, 96.568% below 16.667 ms
21:57:12.226:  ┣tick_sources: min=0 ms, median=0.022 ms, max=565.05 ms, 99th percentile=0.107 ms
21:57:12.226:  ┣output_frame: min=0.071 ms, median=0.374 ms, max=37.798 ms, 99th percentile=2.644 ms
21:57:12.226:  ┃ ┗gs_context(video->graphics): min=0.07 ms, median=0.373 ms, max=37.797 ms, 99th percentile=2.643 ms
21:57:12.226:  ┃   ┣render_video: min=0.019 ms, median=0.263 ms, max=34.687 ms, 99th percentile=1.13 ms
21:57:12.226:  ┃   ┃ ┗render_main_texture: min=0.016 ms, median=0.257 ms, max=34.682 ms, 99th percentile=1.125 ms
21:57:12.226:  ┃   ┗gs_flush: min=0.037 ms, median=0.101 ms, max=10.407 ms, 99th percentile=2.284 ms
21:57:12.226:  ┗render_displays: min=0 ms, median=6.624 ms, max=43.226 ms, 99th percentile=29.126 ms
21:57:12.226: =================================================
21:57:12.226: == Profiler Time Between Calls ==================
21:57:12.226: obs_hotkey_thread(25 ms): min=25.096 ms, median=29.563 ms, max=31.315 ms, 0.333704% within ±2% of 25 ms (0% lower, 99.6663% higher)
21:57:12.226: obs_graphics_thread(16.6667 ms): min=6.03 ms, median=16.682 ms, max=565.199 ms, 30.6397% within ±2% of 16.667 ms (34.4108% lower, 34.9495% higher)
21:57:12.226: =================================================
21:57:12.238: Number of memory leaks: 0

**Comment by royshil** [comment]
@Sven74Muc the latest v of the plugin will not work w obs 28.x
download plugin version 0.5.x or anything before 1.0x
that should be supported in v28

**Comment by Sven74Muc** [comment]
@royshil Thanks so much! Do I miss any important functionallity  with such an old version?

**Comment by royshil** [comment]
@Sven74Muc the major functionality - removing background - exists in all versions of the plugin. but we've worked a lot on robustness and usage. so you may experience degradation in quality, but still should be very usable.
if you have any problems please let us know!
