### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by ifuchs** [occ-ai/obs-backgroundremoval#486]
The link to the Wiki in the Github Readme is faulty:
https://obs-ai.github.io/obs-backgroundremoval/

**Comment by umireon** [comment]
Can you make a PR to fix this?

**Comment by royshil** [comment]
@ifuchs in the readme i can see the correct link - where do you see this problem?

**Comment by ifuchs** [comment]
If I go to that link, I get the following:
![image](https://github.com/occ-ai/obs-backgroundremoval/assets/5650376/d438d303-a519-4926-8226-946c763a158a)

**Comment by umireon** [comment]
Can you make a PR to fix this?

**Comment by royshil** [comment]
@ifuchs where are you getting this link? on `master` the readme link is the correct one 
![image](https://github.com/occ-ai/obs-backgroundremoval/assets/441170/9ad594a1-e279-45aa-943f-e7a5598db350)

**Comment by umireon** [comment]
I suppose this bad link is on the release page and already fixed.
