### ISSUE TITLE
Please tell me the right instructions to install the plugin on WIndows

### ISSUE THREAD

**Issue by crowlsyong** [occ-ai/obs-backgroundremoval#489]
Describe the bug

Running $ flatpak install com.obsproject.Studio.Plugin.BackgroundRemoval on Windows results in an error. Additional configuration is required to make it work on Windows, and the provided guide does not explain how to do that, making the instructions unclear.

To Reproduce

Open a Windows command prompt or PowerShell.
Run the command: $ flatpak install com.obsproject.Studio.Plugin.BackgroundRemoval
Observe the error indicating that Flatpak is not recognized as a valid command.
Expected behavior

I expected the command to install the OBS Studio Plugin Background Removal on Windows as described in the provided guide.

Screenshots

N/A

Log and Crash Report

N/A

Desktop

OS: Windows 10 (or your specific Windows version)
Browser: N/A
Plugin Version: N/A (Please specify if known)
OBS Version: N/A (Please specify if known)
Additional context

The issue occurs because Flatpak is a package management system primarily designed for Linux, and attempting to use it on Windows results in the "Flatpak is not recognized" error. The guide does not provide instructions for Windows users, leading to confusion. It would be helpful to include Windows-specific installation instructions or clarify that Flatpak is not intended for use on Windows.

**Comment by crowlsyong** [comment]
PowerShell 7.3.9
PS C:\Windows\System32> flatpak install com.obsproject.Studio.Plugin.BackgroundRemoval
flatpak: The term 'flatpak' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Windows\System32> github/scripts/Build-Windows.ps1 -Target x64 -CMakeGenerator "Visual Studio 17 2022"
github/scripts/Build-Windows.ps1: The term 'github/scripts/Build-Windows.ps1' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Windows\System32>
PS C:\Windows\System32> .github/scripts/Build-Windows.ps1 -Target x64 -CMakeGenerator "Visual Studio 17 2022"
.github/scripts/Build-Windows.ps1: The term '.github/scripts/Build-Windows.ps1' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Windows\System32> .github/scripts/Build-Windows.ps1 -Target x64 -CMakeGenerator "Visual Studio 17 2022"
.github/scripts/Build-Windows.ps1: The term '.github/scripts/Build-Windows.ps1' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Windows\System32>

None of the windows instructions work.

**Comment by royshil** [comment]
On Windows you can download https://github.com/occ-ai/obs-backgroundremoval/releases/download/1.1.7/obs-backgroundremoval-1.1.7-windows-x64-Installer.exe and double click it to install

**Comment by RheeUK** [comment]
I run this on an environment where we get this when using exe. The zip files do not work.

![image](https://github.com/occ-ai/obs-backgroundremoval/assets/133206440/10b7b52b-2cca-43a0-a7be-80b63c2c395d)

**Comment by umireon** [comment]
Signing our installer won't fix this error screen. When so many people download our installer from the new URL, this error screen will be gone. Thus, it will take some time to resolve this issue of the error screen.

**Comment by RheeUK** [comment]
> Signing our installer won't fix this error screen. When so many people download our installer from the new URL, this error screen will be gone. Thus, it will take some time to resolve this issue of the error screen.

I cannot bypass organisation policies to install it I'm afraid. 
How do I install manually please?

**Comment by umireon** [comment]
@RheeUK  Can you file a new issue for assistance?

**Comment by umireon** [comment]
@Smurfettesims Please do not post an off-topic comment on stalled issues.
