### ISSUE TITLE
using the newest obs-background removal for ubuntu22.04 obs installed with snap

### ISSUE THREAD

**Issue by altineller** [occ-ai/obs-backgroundremoval#490]
Hello,

I am using ubuntu22.04 and I have installed obs tru snap. Upon starting the obs, it will give a warning about "Background Removal - Update available!"

I am very interested this plugin and I would like to try. How can we get it going for the snap version? Maybe I should be using the apt package? Or do I have to compile it from src?

Best Regards,
Can

**Comment by incomer17** [comment]
I have the same problem. Which folders should be present in snap/obs... in which to unpack the plugin?
