### ISSUE TITLE
"Failed to create ONNXRuntime session. Error code: 5"  error.

### ISSUE THREAD

**Issue by universitystudentdesu** [occ-ai/obs-backgroundremoval#491]
hello.
Im Japanese.
Imnot good at wiritiong English.

I was  building the obs pluguin(background removal), but when I tried the built version, the following error appeared in the log.
Is there any solution.
![image](https://github.com/occ-ai/obs-backgroundremoval/assets/151612016/705cc320-c772-45eb-bf54-b42ee37a9ae0)

**Comment by umireon** [comment]
僕はメンテナですが日本人なので日本語で書いてもらって大丈夫です

**Comment by universitystudentdesu** [comment]
background removalをビルドして、機能を試してみたのですが、画像の一番上に出ているonnxruntimeのエラーが出てしまっていて改善がわからないです。
![スクリーンショット (14)](https://github.com/occ-ai/obs-backgroundremoval/assets/151612016/12811086-00cd-44fb-89b5-bbde7073a246)
また、ログが以下のようになってしまいます。
![スクリーンショット (15)](https://github.com/occ-ai/obs-backgroundremoval/assets/151612016/8d722306-e3f1-4bc3-a463-8dc4a8d6a2ae)
原因が全く分からないのです。

**Comment by umireon** [comment]
どうやってインストールしたか手順をできるだけ詳細に書いてください。またOBSのログファイルを添付してください。OBSのログファイルはヘルプメニューから取得できます。ログファイルのスクリーンショットはやめてください。
OBSのバージョン、Windowsのバージョン、CUDAが入っているならCUDAのバージョンも記載してください。

**Comment by universitystudentdesu** [comment]
windows powershell でリポジトリのクローンを作成し、それをCMakeでビルドしました。
obsのlogです
https://obsproject.com/logs/RPRBNQE1reRuVDwr
[2023-11-22 15-15-55.txt](https://github.com/occ-ai/obs-backgroundremoval/files/13434363/2023-11-22.15-15-55.txt)

obs：29.1.3
windous：22H2
になっています。
backgroundremovalのソースコードを一部変更しています。
変更後のソースコードです。
[background-filter.txt](https://github.com/occ-ai/obs-backgroundremoval/files/13434396/background-filter.txt)

**Comment by universitystudentdesu** [comment]
background removalのバージョンは1.1.7です

**Comment by umireon** [comment]
こちらにビルド済みのバイナリのインストーラーがありますので、まずは自力でビルドするのではなくインストーラーを試してもらえますか？
SmartScreenの警告とかが出るかもしれませんが、無効化はできるはずなので試してみてください。
https://github.com/occ-ai/obs-backgroundremoval/releases/download/1.1.7/obs-backgroundremoval-1.1.7-windows-x64-Installer.exe

**Comment by umireon** [comment]
原因としては機械学習のモデルファイルが正しくdata以下にインストールされていないのだと思います。Windowsで自力でビルドするメリットは特にないので、ビルド済みバイナリが使えるならそちらの方が良いです。

**Comment by universitystudentdesu** [comment]
ありがとうございました。解決いたしました。
