### ISSUE TITLE
Missing dependency on libqt6-widgets6

### ISSUE THREAD

**Issue by fuglede** [occ-ai/obs-backgroundremoval#492]
I have installed `obs-backgroundremoval` using the `.deb` on Debian while having picked up OBS itself from the Debian Testing. When I try to add an effect filter to a video capture device, the background removal filter does not show up.

```
$ apt show obs-studio
Package: obs-studio
Version: 29.1.3+dfsg-2
Priority: optional
Section: video
Maintainer: Debian Multimedia Maintainers <debian-multimedia@lists.debian.org>
Installed-Size: 21.4 MB

$ apt show obs-backgroundremoval
Package: obs-backgroundremoval
Version: 1.1.7
Status: install ok installed
Priority: optional
Section: devel
Maintainer: roy.shil@gmail.com
Installed-Size: 427 MB
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: obs-backgroundremoval built using CMake
```

![obs-backgroundremoval](https://github.com/occ-ai/obs-backgroundremoval/assets/6169306/afd7e1f1-7a49-41fa-8d43-8da306e8d622)

One relevant thing that then shows up in the log is this:

```
09:55:21.313: os_dlopen(/usr//lib/x86_64-linux-gnu/obs-plugins/obs-backgroundremoval.so->/usr//lib/x86_64-linux-gnu/obs-plugins/obs-backgroundremoval.so): libQt6Widgets.so.6: cannot open shared object file: No such file or directory
09:55:21.313: 
09:55:21.313: Module '/usr//lib/x86_64-linux-gnu/obs-plugins/obs-backgroundremoval.so' not loaded
```

Indeed, after installing `libqt6-widgets6`, the effect filter shows up. So it seems this ought to be added as a dependency, or at least spelled out in the docs that this could be an issue.

One thing that confused me a bit is that [the release page](https://github.com/occ-ai/obs-backgroundremoval/releases/tag/1.1.7) suggests that there are installation instructions on https://obs-ai.github.io/obs-backgroundremoval/, but that page 404s because it looks like `obs-ai` has been renamed to `occ-ai`.

**Comment by umireon** [comment]
The URL on the release page was fixed.

**Comment by umireon** [comment]
@royshil We decided not to support Debian by the deb package so can we close this issue as not planned?

**Comment by royshil** [comment]
i removed Qt dep in #538 - woudn't that help with Debian?

**Comment by royshil** [comment]
#538 was merged and removed Qt dependency.

**Comment by umireon** [comment]
@royshil Can we close this issue as stalled?
