### ISSUE TITLE
@Lucretia Please do not post any offensive contents.

### ISSUE THREAD

**Issue by Lucretia** [occ-ai/obs-backgroundremoval#493]
@Lucretia Please do not post any offensive contents.

_Originally posted by @umireon in https://github.com/occ-ai/obs-backgroundremoval/issues/436#issuecomment-1836507540_
            
I didn't post anything offensive, if you think what you posted to me was reasonable, I suggest you think about how you would like being told to use a different distribution because you can't be bothered.

**Comment by Lucretia** [comment]
> ```
>           @Lucretia Please do not post any offensive contents.
> ```
> 
> _Originally posted by @umireon in [#436 (comment)](https://github.com/occ-ai/obs-backgroundremoval/issues/436#issuecomment-1836507540)_
> 
> I didn't post anything offensive, if you think what you posted to me was reasonable, I suggest you think about how you would like being told to use a different distribution because you can't be bothered.

And it would be better if you actually engaged instead of palming people off, blocking them from commenting, deleting their comments and making false accusations.

**Comment by Lucretia** [comment]
I didn't demand shit, I asked about something, you went out of YOUR way to be offensive.

**Comment by umireon** [comment]
@royshil I emailed you. Can you check it?
