### ISSUE TITLE
Install triggers smart screen!

### ISSUE THREAD

**Issue by MrHinsh** [occ-ai/obs-backgroundremoval#499]
I have added your app to Winget:

https://github.com/microsoft/winget-pkgs/pull/131370

I'll submit a PR with an auto updater!

**Comment by MrHinsh** [comment]
Also on manual download:

![image](https://github.com/occ-ai/obs-backgroundremoval/assets/5205575/8bc204d2-1b83-408b-8680-a83c9a19095e)

**Comment by umireon** [comment]
SmartScreen will disappear when many people download our plugin successfully. We recently changed the distribution URL and Microsoft has not yet trusted our new page. I suppose we can do nothing about SmartScreen.

**Comment by MrHinsh** [comment]
![image](https://github.com/occ-ai/obs-backgroundremoval/assets/5205575/139b6df5-92e9-48a5-a6c9-fbf04f0ffad4)

We will just have to wait!

**Comment by MrHinsh** [comment]
I belive its likley being triggered becasue the "Comapny Name" is missing from the meta data.

You can also submit your application to https://learn.microsoft.com/en-us/windows/security/operating-system-security/virus-and-threat-protection/microsoft-defender-smartscreen/#submit-files-to-microsoft-defender-smartscreen-for-review

**Comment by umireon** [comment]
Oh thanks! Can you make a PR to add company name to the metadata?

**Comment by MrHinsh** [comment]
Sorry, I have no idea how to do that with CMake, which I have never used.

**Comment by royshil** [comment]
I think this needs to be fixed in the OBS plugin template files. 
I can try to dig around. But so far my research came up short, it looks like the installer is in fact filling up the author information.

@MrHinsh How do you find those details?
If I know how I can make experiments and see if it affects the output

**Comment by MrHinsh** [comment]
It had author, but no company. 

I just googled "view meta data in executable files on windows" and used a tool. I'm not at my computer to check, but it was installable with Winget.

I compared it to my file that downloads fine without triggering SmartScreen.

Did you submit your app to the smart screen check site?

**Comment by MrHinsh** [comment]
:) Back at my computer! 

I used "exiftool".

```
❯ exiftool "C:\Users\MartinHinshelwood(He\Downloads\obs-backgroundremoval-1.1.8-windows-x64-Installer.exe"
ExifTool Version Number         : 12.70
File Name                       : obs-backgroundremoval-1.1.8-windows-x64-Installer.exe
Directory                       : C:/Users/MartinHinshelwood(He/Downloads
File Size                       : 37 MB
File Modification Date/Time     : 2023:12:20 08:58:19+00:00
File Access Date/Time           : 2023:12:27 10:24:08+00:00
File Creation Date/Time         : 2023:12:20 08:58:08+00:00
File Permissions                : -rw-rw-rw-
File Type                       : Win32 EXE
File Type Extension             : exe
MIME Type                       : application/octet-stream
Machine Type                    : Intel 386 or later, and compatibles
Time Stamp                      : 2023:02:15 14:54:16+00:00
Image File Characteristics      : No relocs, Executable, No line numbers, No symbols, Bytes reversed lo, 32-bit, Bytes reversed hi
PE Type                         : PE32
Linker Version                  : 2.25
Code Size                       : 741888
Initialized Data Size           : 89600
Uninitialized Data Size         : 0
Entry Point                     : 0xb5eec
OS Version                      : 6.1
Image Version                   : 6.0
Subsystem Version               : 6.1
Subsystem                       : Windows GUI
File Version Number             : 0.0.0.0
Product Version Number          : 0.0.0.0
File Flags Mask                 : 0x003f
File Flags                      : (none)
File OS                         : Win32
Object File Type                : Executable application
File Subtype                    : 0
Language Code                   : Neutral
Character Set                   : Unicode
Comments                        : This installation was built with Inno Setup.
Company Name                    : Roy Shilkrot
File Description                : obs-backgroundremoval Setup
File Version                    :
Legal Copyright                 :
Original File Name              :
Product Name                    : obs-backgroundremoval
Product Version                 : 1.1.8
```

I see that the company name is set to "Roy Shilkrot" and I have submitted your tool.

SmartScreen being triggered is not normal, and I have anumber of executable tools that do not trigger it and never did. I wonder what the issue is...

**Comment by MrHinsh** [comment]
@royshil did you change any of the metadata recently? that could have triggered this!

**Comment by umireon** [comment]
@MrHinsh Our older installers are available on [the releases page](https://github.com/occ-ai/obs-backgroundremoval/releases). Could you kindly investigate the difference between the current one and the older one that does not cause the SmartScreen? We will appreciate your contribution so much! Thanks in advance!

**Comment by MrHinsh** [comment]
I just checked all the way back to Betas and they all trigger SmartScreen. That implies that you have built no trust with the installer as it is not recognising that they are all from the same pubisher.

**Comment by umireon** [comment]
I don't think there is an instant solution to erase SmartScreen and what we can do is just wait for it to go until Microsoft recognizes our product is safe because so many people download it.

**Comment by MrHinsh** [comment]
@umireon this tool has been around for years, and typically files with low downloads takes 2-8 weeks to recognise. 

If this is not happening then there must be something that is preventing it.

**Comment by MrHinsh** [comment]
The URL does not trigger, its the file itself.

Have you submited your application to https://learn.microsoft.com/en-us/windows/security/operating-system-security/virus-and-threat-protection/microsoft-defender-smartscreen/#submit-files-to-microsoft-defender-smartscreen-for-review?

**Comment by umireon** [comment]
@MrHinsh Could you tell us the detail of what metadata our installer should have or be fixed?

**Comment by MrHinsh** [comment]
See https://github.com/occ-ai/obs-backgroundremoval/issues/499#issuecomment-1871010349 for the comparison to another app that I have previously supplied above.

The version number are not filled out. To me that would imply a local build rather than a shared product. 🤷‍♂️

I feel I have done all I can to help here. You can do something with it or not. As you see from other tickets this will disable the ability for most work computers as most large companies prevent smart screen bypass.

I suggest that you:

- update the various meta data tags to enable the publisher to be more identifiable as per the examples I have given above.
- submit your installer to the smartscreen validation check page I added above.

**Comment by umireon** [comment]
@MrHinsh I'm trying to add the metadata that you suggested us to add. The new installer with the metadata will be available soon on #505.

**Comment by umireon** [comment]
@MrHinsh Could you check if the following new installer has the metadata that you expect?
https://github.com/occ-ai/obs-backgroundremoval/actions/runs/7347828061#:~:text=obs%2Dbackgroundremoval%2D1.1.8%2Dwindows%2Dx64%2D162c279e2

**Comment by umireon** [comment]
#505 was merged!

**Comment by umireon** [comment]
@royshil Can you submit our installer to Microsoft to suppress Smart Screen?
https://learn.microsoft.com/en-us/windows/security/operating-system-security/virus-and-threat-protection/microsoft-defender-smartscreen/#submit-files-to-microsoft-defender-smartscreen-for-review

**Comment by royshil** [comment]
i believe @MrHinsh already submitted our tool
on my Windows 11 PC the installer doesn't trigger SmartScreen, it only has the standard warning about unknown publisher...
maybe MSFT has already "approved"?

**Comment by MrHinsh** [comment]
I did submit. 

If SmartScreen is passing then I'll resubmit to Winget and see if it passes there.

**Comment by umireon** [comment]
Seems to be completed.
