### ISSUE TITLE
Add macOS' built-in Vision API as option

### ISSUE THREAD

**Issue by pr0pz** [occ-ai/obs-backgroundremoval#501]
**Is your feature request related to a problem? Please describe.**
This plugin is great as I need the blur on my background.

The CPU usage get a little bit high sometimes and It would be awesome if mac users could have the choice to use the built in vision api. There is an OBS plugin for that (https://github.com/gxalpha/obs-mac-backgroundremoval) but the plugin just removes the background without any extra options.

**Describe the solution you'd like**
I was thinking about a dropdown under advanced settings where i can switch from CPU to Vision API for mac users.

**Comment by umireon** [comment]
The matt of Vision API was implemented before and it revealed that the CPU impact of Vision API is worse than the inference of ONNX Runtime. The quality of Matt by Vision API is better than the ONNX Runtime one.

You cannot expect Vision API for lower CPU usage but do you still want us to implement Vision API Matt?

**Comment by umireon** [comment]
@royshil Can we close this request as this seems not to be a reasonable option for us?

**Comment by royshil** [comment]
we can close this issue and focus on onnxruntime executor for Apple Metal
