### ISSUE TITLE
Cannot install plugin using PacStall on ubuntu 20.04

### ISSUE THREAD

**Issue by verma-alan** [occ-ai/obs-backgroundremoval#503]
I am using the following command to install the plugin :

`pacstall -I obs-backgroundremoval-git
`
However, I receive the following error:

[!] ERROR: This Pacscript does not work on focal/20.04

Could someone guide me as to how I can make this plugin work on my current OS and could you provide support for ubuntu 20.04 ?

**Comment by umireon** [comment]
We cannot provide the support for 20.04. Please update your Ubuntu distribution to 22.04 or later. Thanks!
