### ISSUE TITLE
The Package is not installed under MacOS for OBS, or am I missing some procedure?

### ISSUE THREAD

**Issue by mkultan** [occ-ai/obs-backgroundremoval#511]
**Describe the bug**

The Package is not installed under MacOS for OBS, or am I missing some procedure?

**To Reproduce**

1. Download recent Installer
2. Install
3. Cannot see the Effect Filter in the list

 - OS: \[e.g. iOS\] Sonoma 14
 -  - Plugin Version: Background Removal / Virtual Green-screen & Low-Light Enhance v1.1.8
 - OBS Version: 29.0.0

**Additional context**

**Comment by umireon** [comment]
@mkultan 
Please post here the log for further investigation.

Upload your OBS log file here (Help>Log Files>Show Log Files) to help us find cause of the problem.

**Comment by umireon** [comment]
And upload the screenshot image that indicates that our plugin is not available.

**Comment by joe-allen** [comment]
@mkultan, I just ran into the same issue. Completely closing OBS and reopening solved for me.

**Comment by codermaniaa** [comment]
Good to know this

**Comment by umireon** [comment]
@royshil Can we close this issue as stalled? This issue lacks details and is likely to be a catch-all issue so we need to close this as soon as possible.

**Comment by royshil** [comment]
stalled
