### ISSUE TITLE
Windows installer doesn't need to add a start menu item

### ISSUE THREAD

**Issue by iandouglas** [occ-ai/obs-backgroundremoval#517]
**Describe the bug**

Running the Windows installer wants to make a Start Menu item for the plugin, which is unnecessary.

**To Reproduce**

1. Run the installer, pick the path for OBS, etc, but then it tells you it's making a Start Menu entry, not as an option. But it's unnecessary even as an option.

**Expected behavior**

Just install the plugin.

**Screenshots**

Can't give a screenshot, because trying to reinstall doesn't show the Start Menu option, it just installs the plugin.

**Desktop (please complete the following information):**

 - OS: Windows 11
 - Plugin Version: 1.1.9

**Comment by umireon** [comment]
https://jrsoftware.org/ishelp/index.php?topic=setup_disableprogramgrouppage

**Comment by umireon** [comment]
This should be resolved.
