### ISSUE TITLE
filter is not shown in list

### ISSUE THREAD

**Issue by cnoam** [occ-ai/obs-backgroundremoval#521]
probably duplicate of https://github.com/orgs/occ-ai/discussions/507 (which is locked for comments)
I see the same behavior as in the above discussion. The filter is not shown. 
```
$ flatpak install com.obsproject.Studio.Plugin.BackgroundRemoval
Looking for matches…


        ID                                                    Branch        Op       Remote        Download
 1. [✓] com.obsproject.Studio.Plugin.BackgroundRemoval        stable        i        flathub       168.7 MB / 166.8 MB

Installation complete.

$ obs --version
OBS Studio - 30.0.1

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

$ flatpak list | grep -i remov
Background Removal	com.obsproject.Studio.Plugin.BackgroundRemoval	1.1.8	stable	system

$ whereis obs
obs: /usr/bin/obs /usr/include/obs /usr/share/obs
```

**Comment by umireon** [comment]
Can you post here the log of your OBS and a screenshot that indicates our plugin not to be loaded?

Your problem is not a duplicate with the discussion you wrote and you are required to describe your situation thoroughly.

**Comment by cnoam** [comment]
Here is the output of Menu Help | Log files | View current log:

PS: I did not see installation instructions, so just ran "flatpak install". Should I do anything else?


18:01:35.205: Using EGL/X11
18:01:35.206: CPU Name: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
18:01:35.206: CPU Speed: 3184.149MHz
18:01:35.206: Physical Cores: 4, Logical Cores: 8
18:01:35.206: Physical Memory: 31951MB Total, 6945MB Free
18:01:35.206: Kernel Version: Linux 6.2.0-39-generic
18:01:35.206: Distribution: "Ubuntu" "22.04"
18:01:35.206: Desktop Environment: ubuntu:GNOME (ubuntu)
18:01:35.206: Session Type: x11
18:01:35.206: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
18:01:35.209: Qt Version: 6.2.4 (runtime), 6.2.4 (compiled)
18:01:35.209: Portable mode: false
18:01:35.278: OBS 30.0.1 (linux)
18:01:35.278: ---------------------------------
18:01:35.278: ---------------------------------
18:01:35.278: audio settings reset:
18:01:35.278: 	samples per sec: 48000
18:01:35.278: 	speakers:        2
18:01:35.278: 	max buffering:   960 milliseconds
18:01:35.278: 	buffering type:  dynamically increasing
18:01:35.291: ---------------------------------
18:01:35.291: Initializing OpenGL...
18:01:35.386: Loading up OpenGL on adapter Intel Mesa Intel(R) UHD Graphics 620 (KBL GT2)
18:01:35.387: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1, shading language 4.60
18:01:35.435: ---------------------------------
18:01:35.435: video settings reset:
18:01:35.435: 	base resolution:   1920x1080
18:01:35.435: 	output resolution: 1920x1080
18:01:35.435: 	downscale filter:  Bicubic
18:01:35.435: 	fps:               30/1
18:01:35.435: 	format:            NV12
18:01:35.435: 	YUV mode:          Rec. 709/Partial
18:01:35.436: NV12 texture support not available
18:01:35.436: P010 texture support not available
18:01:35.444: Audio monitoring device:
18:01:35.444: 	name: Default
18:01:35.444: 	id: default
18:01:35.444: ---------------------------------
18:01:35.459: No AJA devices found, skipping loading AJA UI plugin
18:01:35.459: Failed to initialize module 'aja-output-ui.so'
18:01:35.473: No AJA devices found, skipping loading AJA plugin
18:01:35.473: Failed to initialize module 'aja.so'
18:01:35.483: Failed to load 'en-US' text for module: 'decklink-captions.so'
18:01:35.493: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
18:01:35.503: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
18:01:35.503: Failed to initialize module 'decklink.so'
18:01:35.788: [pipewire] No captures available
18:01:35.821: [obs-browser]: Version 2.23.1
18:01:35.821: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures.2594+g17f8588+chromium-103.0.5060.134 (compiled)
18:01:35.995: VAAPI: API version 1.14
18:01:35.996: FFmpeg VAAPI H264 encoding supported
18:01:35.999: VAAPI: Failed to initialize display in vaapi_device_hevc_supported
18:01:35.999: FFmpeg VAAPI HEVC encoding not supported
18:01:36.079: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.3.4 | RPC Version: 1)
18:01:36.079: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.2.4 | Qt version (run-time): 6.2.4
18:01:36.079: [obs-websocket] [obs_module_load] Linked ASIO Version: 101801
18:01:36.086: [obs-websocket] [obs_module_load] Module loaded.
18:01:36.129: [vlc-video]: VLC 3.0.16 Vetinari found, VLC video source enabled
18:01:36.129: ---------------------------------
18:01:36.129:   Loaded Modules:
18:01:36.129:     vlc-video.so
18:01:36.129:     text-freetype2.so
18:01:36.129:     rtmp-services.so
18:01:36.129:     obs-x264.so
18:01:36.129:     obs-websocket.so
18:01:36.129:     obs-vst.so
18:01:36.129:     obs-transitions.so
18:01:36.129:     obs-qsv11.so
18:01:36.129:     obs-outputs.so
18:01:36.129:     obs-libfdk.so
18:01:36.129:     obs-filters.so
18:01:36.129:     obs-ffmpeg.so
18:01:36.129:     obs-browser.so
18:01:36.129:     linux-v4l2.so
18:01:36.129:     linux-pulseaudio.so
18:01:36.129:     linux-pipewire.so
18:01:36.129:     linux-jack.so
18:01:36.129:     linux-capture.so
18:01:36.129:     linux-alsa.so
18:01:36.130:     image-source.so
18:01:36.130:     frontend-tools.so
18:01:36.130:     decklink-output-ui.so
18:01:36.130:     decklink-captions.so
18:01:36.130: ---------------------------------
18:01:36.130: QWidget::setTabOrder: 'first' and 'second' must be in the same window
18:01:36.130: ==== Startup complete ===============================================
18:01:36.133: Switched to Preview/Program mode
18:01:36.133: ------------------------------------------------
18:01:36.196: All scene data cleared
18:01:36.196: ------------------------------------------------
18:01:36.199: pulse-input: Server name: 'pulseaudio 15.99.1'
18:01:36.199: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
18:01:36.199: pulse-input: Started recording from 'alsa_output.pci-0000_00_1f.3.analog-stereo.monitor' (default)
18:01:36.200: [Loaded global audio device]: 'Desktop Audio'
18:01:36.200: pulse-input: Server name: 'pulseaudio 15.99.1'
18:01:36.200: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
18:01:36.200: pulse-input: Started recording from 'alsa_input.pci-0000_00_1f.3.analog-stereo' (default)
18:01:36.201: [Loaded global audio device]: 'Mic/Aux'
18:01:36.201:     - filter: 'Noise Suppression' (noise_suppress_filter_v2)
18:01:36.202: v4l2-input: Start capture from /dev/video2
18:01:36.202: v4l2-input: Unable to open device
18:01:36.202: v4l2-input: Initialization failed, errno: No such file or directory
18:01:36.203: [window-capture: 'Window Capture (Xcomposite)'] update settings:
18:01:36.203: 	title: Terminal
18:01:36.203: 	class: gnome-terminal-server
18:01:36.203: 
18:01:36.204: xshm-input: Geometry 1920x1080 @ 2560,360
18:01:36.218: [window-capture: 'Window Cap'] update settings:
18:01:36.218: 	title: unknown
18:01:36.218: 	class: unknown
18:01:36.218: 
18:01:36.220: Switched to scene 'cam with background removal blur'
18:01:36.221: User switched Program to scene 'terminal+web'
18:01:36.223: ------------------------------------------------
18:01:36.223: Loaded scenes:
18:01:36.223: - scene 'Scene':
18:01:36.223:     - source: 'Text (FreeType 2)' (text_ft2_source_v2)
18:01:36.223: - scene 'cam with background removal blur':
18:01:36.223:     - source: 'Video Capture Device (V4L2)' (v4l2_input)
18:01:36.223: - scene 'webcam':
18:01:36.223:     - source: 'Video Capture Device (V4L2)' (v4l2_input)
18:01:36.223: - scene 'terminal+web':
18:01:36.223:     - source: 'Window Capture (Xcomposite)' (xcomposite_input)
18:01:36.223:     - source: 'Video Capture Device (V4L2)' (v4l2_input)
18:01:36.223: - scene 'fullscreen+web':
18:01:36.223:     - source: 'Screen Capture (XSHM)' (xshm_input)
18:01:36.223:     - source: 'Text (FreeType 2)' (text_ft2_source_v2)
18:01:36.223:     - source: 'Video Capture Device (V4L2)' (v4l2_input)
18:01:36.223: - scene 'jupyter':
18:01:36.223:     - source: 'Window Cap' (xcomposite_input)
18:01:36.223: ------------------------------------------------
18:01:36.751: adding 64 milliseconds of audio buffering, total audio buffering is now 64 milliseconds (source: Mic/Aux)
18:01:36.751:

**Comment by royshil** [comment]
yep OBS never tries to load the plugin.

i bet this is because OBS is expecting the plugin in /usr vs ~/.config ... that's almost all the linux problems

@cnoam can you make sure the plugin installs in the right location?

**Comment by umireon** [comment]
@cnoam By what means your OBS binary is installed? Via Flatpak or something else? And please tell us your Linux distribution.

**Comment by cnoam** [comment]
@royshil : What is the right location for flatpak plugins? (I am not familiar with it)
@umireon : OBS was installed by a friend, and I checked now - looks like apt.  using ubuntu 22.04. 
How do I install if apt was used?
see the first message for more details:
```
$ apt list | grep -i obs-st
obs-studio/jammy,now 30.0.1-0obsproject1~jammy amd64 [installed]
```

If obs was not installed by flatpak, shouldn't flatpak give some message? 

PS:
- The linux installation instructions are a bit scarce . 
- the build instructions mention .github/scripts/build-linux.sh  but  the file name is build-linux

**Comment by umireon** [comment]
We have an official site (the link to it is placed at the top of README.md) that describes the instructions for installation.
For Ubuntu, you can follow this page: https://occ-ai.github.io/obs-backgroundremoval/ubuntu

**Comment by umireon** [comment]
Yes, we have to improve the installation document. Thanks for your feedback!

**Comment by cnoam** [comment]
I installed the DEB package and now the plugin is detected and works fine!

conclusion: Be careful of mixing different installation methods. I recommend to add some sanity check in the plugin installer.

**Comment by umireon** [comment]
We won't add any sanity checker to the installer but improve our documentation.
