### ISSUE TITLE
How to uninstall the plugin?

### ISSUE THREAD

**Issue by quantuminformation** [occ-ai/obs-backgroundremoval#522]
I disabled it yet keep getting it

how do i uninstall it?

![image](https://github.com/occ-ai/obs-backgroundremoval/assets/216566/7f3c40ab-fa23-4ae5-a6f1-97f628e965e3)

**Comment by umireon** [comment]
Here is the uninstallation document: https://github.com/occ-ai/obs-backgroundremoval/blob/main/docs/UNINSTALL.md

**Comment by royshil** [comment]
i think we will remove the updater popup in favor of a more discreet notice in the plugin filter
we already have a bit of text there, so adding something when there's an update is simple

**Comment by quantuminformation** [comment]
also i cant select the colour somehow to use as the screen

**Comment by umireon** [comment]
Please open a separate issue if you want us to help you remove your background.

**Comment by quantuminformation** [comment]
how do i uninstall this plugin

**Comment by umireon** [comment]
Did you check the documentation I put in the link above?

**Comment by umireon** [comment]
Can we close this issue as stalled?

**Comment by royshil** [comment]
stalled
