### ISSUE TITLE
Build without GPU support

### ISSUE THREAD

**Issue by Zahrun** [occ-ai/obs-backgroundremoval#523]
Hi there,

I tried to update obs-backgroundremoval in Nix several months ago in https://github.com/NixOS/nixpkgs/pull/230775, but got stuck by the lack of onnxruntime-gpu in Nix https://github.com/NixOS/nixpkgs/issues/228093. 

As far as I understand, in Nix, they do not allow the loading of external dependency during build process apart from other nix packages (which forces USE_SYSTEM_ONNXRUNTIME).

There is an attempt to add onnxruntime-gpu in https://github.com/NixOS/nixpkgs/pull/260745.

It seems that cuda and onnxruntime-gpu are pretty heavy to compile.

As an alternative, would it be possible to build obs-backgroundremoval without GPU support, with only CPU mode available, that would not require tensorrt_provider_factory.h to build?

**Comment by spikespaz** [comment]
I am also awaiting this change, looking forward to a simpler build process!

**Comment by umireon** [comment]
@Zahrun Can you try #524 ?

**Comment by Zahrun** [comment]
Wow, thank you for the very fast implementation @umireon. I will try it in some time.
