### ISSUE TITLE
suspected use of bad pointer in log message

### ISSUE THREAD

**Issue by cnoam** [occ-ai/obs-backgroundremoval#525]
When running obs from commanline (ubuntu 22.04, obs 30.0 ), I saw this line:
```
info: [obs-backgroundremoval]   Model file path: H�	S
```

It looks like using uninit pointer.

**To Reproduce**
install the plugin ( I used sudo dpkg -i obs-backgroundremoval-1.1.10-x86_64-linux-gnu.deb )

Run OBS from cli.
Close the program (from GUI).
read the terminal text

**Expected behavior**
show empty string.

**Comment by umireon** [comment]
I found the bug on ort-session-utils.cpp. I will open a PR to fix this bug.
