### ISSUE TITLE
1.1.10 version still showing warning install screen

### ISSUE THREAD

**Issue by umireon** [occ-ai/obs-backgroundremoval#527]
### Discussed in https://github.com/orgs/occ-ai/discussions/526

<div type='discussions-op-text'>

<sup>Originally posted by **JHershey69** January 12, 2024</sup>
Running Win10 64 bit, not sure if I have something on my system that would still show that screen. But stil showing.</div>

**Comment by umireon** [comment]
@JHershey69 Please provide here the detailed information about your problem.

**Comment by umireon** [comment]
I don't think we can take any more actions to remove the Smart Screen.

**Comment by royshil** [comment]
we're going to offer the plugin on Winget - that will bypass the installer altogether 
and there are other windows pkg mgmt we can target to overcome the installer flags

**Comment by umireon** [comment]
Can we close this issue as stalled? The author have not post anything.

**Comment by JHershey69** [comment]
You can. The warning was the least of my problems. I couldn't get the plugin to work at all.
