### ISSUE TITLE
Please tell me how I can set up this plugin?

### ISSUE THREAD

**Issue by nishushin** [occ-ai/obs-backgroundremoval#529]
**I have downloaded the OBS studio v30.0.2 and Background Removal plugin. Whilst I can see the Background removal under Effect filters, it doesn't create a black screen for me and not working. I have seen some self help videos but some people are seeing Background Removal under Video/Audio filter as well. Not sure where should I be seeing it and where is the issue. Can someone please help?  **

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log and Crash Report**

Upload your OBS log file here (`Help`>`Log Files`>`Show Log Files`) to help us find cause of the problem.

If OBS is crashing, upload the crash report here as well (`Help`>`Crash Reports`>`Show Crash Reports`).

**Desktop (please complete the following information):**

 - OS: \[e.g. iOS\]
 - Browser: \[e.g. chrome, safari\]
 - Plugin Version: \[e.g. 0.5.1\]
 - OBS Version: \[e.g. 28.02\]

**Additional context**

**Comment by royshil** [comment]
@nishushin so youre adding the filter (under "Effect Filters") to your camera source but not seeing anythign happen?
i'd be happy to see a screenshot of the filter view, e.g. click "Filters" on your cam source and select the BG Removal filter, then screenshot this

**Comment by umireon** [comment]
Can we close this issue as stalled?

**Comment by royshil** [comment]
stalled

**Comment by nishushin** [comment]
Hi,

Apologies I was away sick for a few days, and back today - can we please
discuss?
