### ISSUE TITLE
Find and blur text on image?

### ISSUE THREAD

**Issue by alexeik** [occ-ai/obs-backgroundremoval#531]
i have stream and want to blur defined words .
Can it be possible with this plugin?

**Comment by umireon** [comment]
Can you describe what you want to do in detail with some screenshots?

**Comment by alexeik** [comment]
i Have a game
and want to blur some rendered text on frames
![image](https://github.com/occ-ai/obs-backgroundremoval/assets/318732/01a51e40-4ffa-4ab0-bc21-7de3c0ddd7bc)
On this image i want to blur "Can you hear the silence..." or even Fill with color. 
Doesnt matter how to blur.

**Comment by umireon** [comment]
@royshil What do you think about this suggestion? I suppose that we should create another plugin if we want to implement this feature.

**Comment by umireon** [comment]
@alexeik I don't think our plugin is what you want but https://github.com/Xaymar/obs-StreamFX provides a blur filter what you want.

**Comment by umireon** [comment]
@alexeik You have to build the StreamFX plugin by yourself.
https://github.com/Xaymar/obs-StreamFX/blob/root/BUILDING.md

**Comment by alexeik** [comment]
@umireon u r wrong
it can blur X,Y,X1,Y1 Rectangle
In my example i have dynamic cooridantes of text...
it moves like a chat
and it needs to be OCRed and BLURed on different places on screen

**Comment by alexeik** [comment]
@umireon nice! glad to see it is feasible :)

**Comment by umireon** [comment]
@alexeik Please tell me what platform you use. Mac, Windows, or Ubuntu?

**Comment by alexeik** [comment]
@umireon windows !

**Comment by umireon** [comment]
We can use Windows.Media.Ocr to detect words on the screen. It is on a WinRT platform, and we can use it in the same way as WinRTHttpClient.

**Comment by alexeik** [comment]
@umireon will it work in OSB?

**Comment by royshil** [comment]
I just release the OCR plugin https://github.com/occ-ai/obs-ocr
that's directly in OBS and works on any OS and any Hardware!

I will add to the OCR filter an ability to output a text mask which you can then use with Composite Blur plugin https://obsproject.com/forum/resources/composite-blur.1780/ 
no need for StreamFX.

**Comment by alexeik** [comment]
will it support several masks ?

**Comment by royshil** [comment]
> will it support several masks ?

I think I can make it produce a binary mask with rectangles on the areas where text was detected.
So it's a single mask but it covers multiple text areas.
The blur filter shouldn't care either way.

**Comment by umireon** [comment]
Can we close this issue as this feature will not be implemented in this plugin?

**Comment by royshil** [comment]
yep. closing
@alexeik can you please open an issue on https://github.com/occ-ai/obs-ocr/issues ?

**Comment by alexeik** [comment]
@royshil  done
https://github.com/occ-ai/obs-ocr/issues/7
