### ISSUE TITLE
Green Screen Does Not Work Removal/Virtual Green Screen Plugin

### ISSUE THREAD

**Issue by CyberPoned** [occ-ai/obs-backgroundremoval#532]
I installed the background removal/virtual green screen plugin to try and disguise my background for future content. It is version 1.1.10.0 for Windows. The background removal shows up in effect filters instead of audio/video filters. I am still able to apply it and get my background removed. However, I am unable to choose the color for my background to prep it for an image.

![OBS_GreenScreen_Issue](https://github.com/occ-ai/obs-backgroundremoval/assets/129122667/f1aa3896-cd31-4ae1-87cd-155b71404086)

When I consult YouTube everybody can select the background color in the screenshot I attached.

[2024-01-20 14-39-42.txt](https://github.com/occ-ai/obs-backgroundremoval/files/13999215/2024-01-20.14-39-42.txt)

**Desktop (please complete the following information):**

 - OS: Windows 11
 - Browser: Chrome
 - Plugin Version: obs-backgroundremoval-1.1.10-windows-x64-Installer
 - OBS Version: 30.0.2

**Comment by umireon** [comment]
This plugin works as expected. The video you watched is obsolete.
