### ISSUE TITLE
pop up

### ISSUE THREAD

**Issue by ebonyfax** [occ-ai/obs-backgroundremoval#534]
how do I prevent the 'background removal - update available!" popup from opening every time I access OBS?

**Comment by umireon** [comment]
@royshil

**Comment by royshil** [comment]
Thanks for the issue @ebonyfax 
I think we will remove the popup in favor of a message on the filter config. I see a lot of people are annoyed by the popup..

**Comment by royshil** [comment]
check out #538  for proposed different solution for update available notice

**Comment by royshil** [comment]
we got rid of the popup in #538
