### ISSUE TITLE
Can we remove Qt dependency?

### ISSUE THREAD

**Issue by umireon** [occ-ai/obs-backgroundremoval#536]
Qt dependency causes problems for Debian or some distributions that use older OBS installations. Since the Qt dependency is not critical for our plugin, can we consider removing Qt dependency for better compatibility?

**Comment by umireon** [comment]
@royshil

**Comment by royshil** [comment]
we used Qt for the update dialog - but if we get rid of that we can remove Qt probably
see #538

**Comment by royshil** [comment]
done on master from #538
