### ISSUE TITLE
Can we have another place to communicate with users casually?

### ISSUE THREAD

**Issue by umireon** [occ-ai/obs-backgroundremoval#541]
@royshil I like a Discord server or so on to communicate with users. It would be great if the server is shared among our occ-ai organization.
If you are afraid of increasing support costs, please dismiss this request.

**Comment by royshil** [comment]
yes a discord server sound like a wonderful idea
i'll lookinto what that entails and create one for OCC AI

**Comment by royshil** [comment]
Discord server created https://discord.gg/AubP6DTT8r

**Comment by umireon** [comment]
Can I adjust some server settings for our community? If it is okay, please make me an admin on this server.

**Comment by royshil** [comment]
discord server created.

**Comment by umireon** [comment]
Thank you!
