### ISSUE TITLE
record with alpha channel?

### ISSUE THREAD

**Issue by anandijain** [occ-ai/obs-backgroundremoval#542]
Thank you very much for the plugin.

Currently, if I am just recording my webcam with the plugin on, all of the stuff that is removed is converted to black in the recording playback. It would be really nice to record it with a transparent background so I could edit the recording on top of other material during video editing. 

Is this possible?

Thanks

**Comment by umireon** [comment]
@royshil Can we close this issue as stalled?

**Comment by royshil** [comment]
stalled
