### ISSUE TITLE
Plugin installs, loads, but does not appear in filter list

### ISSUE THREAD

**Issue by damienstanton** [occ-ai/obs-backgroundremoval#543]
**Describe the bug**

The plugin is installing but not appearing in the list of available plugins, so cannot currently be used.

**To Reproduce**

- Install the plugin from the lates GitHub release tag.
- Open OBS
- Right-click input source > filters > click `+` for Audio/Video filter.

**Expected behavior**

`obs-backgroundremoval` should appear in the list. It does not.

**Screenshots**
<img width="286" alt="Screenshot 2024-01-31 at 4 20 54 PM" src="https://github.com/occ-ai/obs-backgroundremoval/assets/4822375/26755782-4244-4150-9135-6e29e1f0203e">

**Log and Crash Report**

Here is relevant snippets of the log. We see that the plugin has loaded successfully
```
16:17:37.154:   Loaded Modules:
16:17:37.154:     obs-backgroundremoval
16:17:37.154:     vlc-video
16:17:37.154:     text-freetype2
16:17:37.154:     rtmp-services
16:17:37.154:     obs-x264
16:17:37.154:     obs-websocket
16:17:37.154:     obs-vst
16:17:37.154:     obs-transitions
16:17:37.154:     obs-outputs
16:17:37.154:     obs-filters
16:17:37.154:     obs-ffmpeg
16:17:37.154:     obs-browser
16:17:37.154:     mac-virtualcam
16:17:37.154:     mac-videotoolbox
16:17:37.154:     mac-syphon
16:17:37.154:     mac-capture
16:17:37.154:     mac-avcapture
16:17:37.154:     image-source
16:17:37.154:     frontend-tools
16:17:37.154:     decklink-output-ui
16:17:37.154:     decklink-captions
16:17:37.154:     coreaudio-encoder
```

but that it also is trying to read some `.ini` config that doesn't exist. Why/what is it trying to read here?

```
16:17:37.152: [obs-backgroundremoval] Plugin loaded successfully (version 1.1.10)
16:17:37.152: [obs-backgroundremoval] Failed to open config file /Users/dstanton006/Library/Application Support/obs-studio/plugin_config/obs-backgroundremoval/config.ini
16:17:37.152: [obs-backgroundremoval] Failed to open config file /Users/dstanton006/Library/Application Support/obs-studio/plugin_config/obs-backgroundremoval/config.ini
```

**Desktop (please complete the following information):**

 - OS: macOS 14.2.1 (a.k.a. Sonoma)
 - Browser: n/a
 - Plugin Version: `1.1.10`
 - OBS Version: `29.1.3`

**Comment by royshil** [comment]
You will find it in Effect filters
It doesn't appear in Audio/video filters.

**Comment by damienstanton** [comment]
Ah, that was it. Thank you! I believe I must have seen an old instructional video. Closing as there does not appear to be any issue here.

**Comment by oleksandr-jr** [comment]
Ok, but for me it's not visible even in Effect filters

**Comment by eXtrem0us** [comment]
> Ok, but for me it's not visible even in Effect filters

I have the same issue. My obs version is 29.1.2 and both obs and backgroundremoval plugin are installed using deb packages.
![image](https://github.com/user-attachments/assets/7b0d94d7-4e47-49ce-a648-50a508269373)
and here is the log of running obs in terminal:
```
info: [obs-backgroundremoval] Plugin loaded successfully (version 1.1.13)
info: [obs-backgroundremoval] Failed to open config file /home/mehdi/.config/obs-studio/plugin_config/obs-backgroundremoval/config.ini
info: [obs-backgroundremoval] Failed to open config file /home/mehdi/.config/obs-studio/plugin_config/obs-backgroundremoval/config.ini
info: [obs-backgroundremoval] Latest release is 1.1.13
```
I even created a blank config.ini, so that it somehow bypass the error message. The error message was gone. But yet the plugin wasn't loaded.
