### ISSUE TITLE
[NixOS] Unable to get model filename models/mediapipe.onnx

### ISSUE THREAD

**Issue by Zahrun** [occ-ai/obs-backgroundremoval#544]
**Describe the bug**

I’m updating the plugin in Nix at https://github.com/NixOS/nixpkgs/pull/230775.
It builds fine but then when loaded in OBS, it fails to "get model filename models/mediapipe.onnx"

**To Reproduce**

1. In NixOS, you can have this in your configuration file:
``
{ config, pkgs, lib, ... }:
let
  backgroundremoval = import (builtins.fetchTarball {
    url = "https://github.com/Zahrun/nixpkgs/archive/upd/obs-backgroundremoval-2.tar.gz";
  }) {config = removeAttrs config.nixpkgs.config [ "packageOverrides" ];};
in 
{
  environment.systemPackages = with pkgs; [
    (backgroundremoval.wrapOBS {
      plugins = [
        backgroundremoval.obs-studio-plugins.obs-backgroundremoval
      ];
    })
``

**Expected behavior**

obs-backgroundremoval works

**Log and Crash Report**

[2024-02-08 14-01-35.txt](https://github.com/occ-ai/obs-backgroundremoval/files/14206429/2024-02-08.14-01-35.txt)

**Desktop (please complete the following information):**

 - OS: NixOS 23.11
 - Browser: Firefox
 - Plugin Version: 1.1.10
 - OBS Version: 30.0.2

**Additional context**

This is probably a Nix packaging issue rather than an issue in obs-backgroundremoval itself. I’m just wondering if you would have an idea about it. Also how the plugin gets the model file path? Would that work with symlinks?

**Comment by royshil** [comment]
i think maybe it's not taking the models along with it? or not installing them in the plugins folders for OBS?
that would explain why it's missing the file, right?

**Comment by umireon** [comment]
I will investigate this.

**Comment by Zahrun** [comment]
Fixed it by replacing `"$out"/usr` with `"$out"` in the cmake install line
```
    cmake --install build_x86_64 --prefix "$out"/usr
```
