### ISSUE TITLE
Even if you check Disable update check, it will be displayed every time you start OBS.

### ISSUE THREAD

**Issue by ronyironcobra** [occ-ai/obs-backgroundremoval#553]
**Describe the bug**

Even if you check Disable update check, it will be displayed every time you start OBS.

**Desktop (please complete the following information):**

 - OS:ubuntu22.04 ja
 - OBS Version: 30.0.2

**Comment by umireon** [comment]
We are going to remove the update screen. I think it will be deleted on the next release.

**Comment by royshil** [comment]
implemented in latest release, please update.
