### ISSUE TITLE
Background removal doesn't work nicely with the Source Clone plugin from Exeldro.

### ISSUE THREAD

**Issue by WaldoAndFriends** [occ-ai/obs-backgroundremoval#554]
**Describe the bug**
Background removal doesn't work nicely with the Source Clone plugin from Exeldro.
When I add the background removal to a source, and make a clone of the scene where the source is in. The clone still shows the video feed with the background intact. The same is true for when I clone the source directly, the background still shows up.

**To Reproduce**

1. Add the filter to a source
2. Make a Source Clone of the source or scene the source is in
3. The clone doesn't have the removed background.

**Expected behavior**

The source clone should be 1-to-1 the same as the original, so it should have the background removed.

**Screenshots**
![image](https://github.com/occ-ai/obs-backgroundremoval/assets/77986224/85c4438f-3ab3-4c12-8858-67db6f7b3bda)
![image](https://github.com/occ-ai/obs-backgroundremoval/assets/77986224/390b58f7-231d-4dcd-a244-c9dfd5438541)

**Log and Crash Report**
[log.txt](https://github.com/occ-ai/obs-backgroundremoval/files/14540137/log.txt)

**Desktop (please complete the following information):**

 - OS: Windows 11
 - Plugin Version: 1.1.10
 - OBS Version: 30.0.2

**Additional context**
I've also relayed this information to the developer of the Source Clone plugin

**Comment by umireon** [comment]
You can add this plugin to a group

**Comment by WaldoAndFriends** [comment]
Groups don't have the same functionality as Source Clones.
As with a source clone I can create a source once and reuse it in multiple scenes, and add filters to those clones without affecting the original source or the other clones.

So perfect for stuff like a webcam that's used in multiple scenes.

**Comment by umireon** [comment]
Can you check if the method described in https://github.com/occ-ai/obs-backgroundremoval/issues/407 is suitable for you and if is not suitable, can you describe what is the missing feature of the group method?

**Comment by umireon** [comment]
I confirmed that our plugin works with Source Clone perfectly when both of the original source and the cloned source is shown.
![Screenshot 2024-03-09 19-40-24](https://github.com/occ-ai/obs-backgroundremoval/assets/1067855/a3b689c4-c565-49f0-b236-66e114bb486a)

**Comment by umireon** [comment]
@royshil I suggest that we'd like to add an option to let our plugin run the inference even if the source is not shown. What do you think?

**Comment by royshil** [comment]
> @royshil I suggest that we'd like to add an option to let our plugin run the inference even if the source is not shown. What do you think?

sure, that's possible
it can be a boolean option in the settings
