### ISSUE TITLE
Latest update seems to break silhouette coherence

### ISSUE THREAD

**Issue by taoeffect** [occ-ai/obs-backgroundremoval#560]
**Describe the bug**

v1.1.12 on macOS.

Look at how it doesn't follow my face:

![Screenshot 2024-03-15 at 7 35 51 PM](https://github.com/occ-ai/obs-backgroundremoval/assets/138706/96d444ec-94b9-42e0-85ad-bc8167a57e4e)

Here are my settings:

![Screenshot 2024-03-15 at 7 39 37 PM](https://github.com/occ-ai/obs-backgroundremoval/assets/138706/3a3d0a3f-2798-41d9-8b0c-992232638260)
![Screenshot 2024-03-15 at 7 39 34 PM](https://github.com/occ-ai/obs-backgroundremoval/assets/138706/af4457bd-a610-4e56-a6ef-a376a6448f12)
![Screenshot 2024-03-15 at 7 39 41 PM](https://github.com/occ-ai/obs-backgroundremoval/assets/138706/b027316f-8d54-4839-a8ff-c83bbc2ad6ea)

**Desktop (please complete the following information):**

 - OS: macOS 14.2.1
 - Browser: Brave
 - Plugin Version: 1.1.12
 - OBS Version: 30.0.2

**Comment by royshil** [comment]
@taoeffect can you disable "skip based on similarity" and see?

**Comment by taoeffect** [comment]
@royshil Woah - that completely fixed it! Thank you! The only downside was significantly increased CPU usage, but then re-enabling it and dragging the slider from 39 to 44 has completely addressed my issue. Thank you!
