### ISSUE TITLE
Huge latency issue in Linux

### ISSUE THREAD

**Issue by yairmohr** [occ-ai/obs-backgroundremoval#561]
Version 1.1.12 (maybe 1.1.11 too - I happened to skip from 1.1.10 to 1.1.12)  seems to introduce a huge, ~1s latency to any camera feed in OBS on Linux Mint (LM version 21.3, OBS version 30.1). When I uninstalled 1.1.12 and reinstalled 1.1.10 - it was back to no latency whatsoever.
It also caused OBS to take over 30s to even load.

**Comment by umireon** [comment]
@royshil I think we need to revert #556. That PR changes too much part of our plugin and it is hard to investigate what affects what.

**Comment by umireon** [comment]
I'm against stopping using video_tick. I don't think there are almost no benefits to use standalone thread but it adds some complexities to our plugin.

**Comment by royshil** [comment]
@umireon I can revert the thread work and go back to video tick. Let me bring it up this evening

**Comment by umireon** [comment]
Thank you!

**Comment by yairmohr** [comment]
Thank you for fixing this in version 1.1.12 :+1:

**Comment by royshil** [comment]
Closing. Thanks!
