### ISSUE TITLE
Support more than one person

### ISSUE THREAD

**Issue by ambyra** [occ-ai/obs-backgroundremoval#562]
The plugin only seems to support one person. If multiple people are in the camera, the plugin switches randomly back and forth between people, treating one or the other as part of the background to remove.

**Comment by royshil** [comment]
@ambyra Try to remove the "enable threshold" option
That has some extra filters to only keep a big area of the image and that might jump around between people on the frame.

**Comment by umireon** [comment]
@royshil Can we close this issue as completed?

**Comment by royshil** [comment]
completed
