### ISSUE TITLE
Tremendous latency apon diabling source

### ISSUE THREAD

**Issue by DJ-Iceman** [occ-ai/obs-backgroundremoval#567]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log and Crash Report**

Upload your OBS log file here (`Help`>`Log Files`>`Show Log Files`) to help us find cause of the problem.

If OBS is crashing, upload the crash report here as well (`Help`>`Crash Reports`>`Show Crash Reports`).

**Desktop (please complete the following information):**

 - OS: \[e.g. iOS\]
 - Browser: \[e.g. chrome, safari\]
 - Plugin Version: \[e.g. 0.5.1\]
 - OBS Version: \[e.g. 28.02\]

**Additional context**

/*Tremendous latency apon diasbling this filter, i have also tried adjusting the #CPU Treads to no avail even when i hide my camera source it produces a tremendous amount of latency and when the camera is showing the latency subsides 100% so i am quite sure it's the plugin with the bug. I have not had this issue until the current release came out (1.1.13)*/

**Comment by umireon** [comment]
Can you fill the issue template before asking help for us?

**Comment by DJ-Iceman** [comment]
> https://github.com/occ-ai/obs-backgroundremoval/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

https://gyazo.com/a2c11b56b79476691004a4af88ff2a1c
https://gyazo.com/79609efe96bdb077b7966d273a94fe33

**Comment by umireon** [comment]
I have pasted the template into your description. Please edit the issue description. Thanks in advance!

**Comment by umireon** [comment]
What is the lag? The video from camera is delayed or the streaming itself is delayed?

**Comment by umireon** [comment]
Post here the screenshot of your setting screen on our plugin. Some settings impacts CPU quite a lot and you can mitigate the performance impact by changing settings.

**Comment by DJ-Iceman** [comment]
> What is the lag? The video from camera is delayed or the streaming itself is delayed?
The camera Backround removal Plugin/Filter is causing lagg when it is disabled or a hidden transition since the new release

**Comment by DJ-Iceman** [comment]
> Post here the screenshot of your setting screen on our plugin. Some settings impacts CPU usage quite a lot and you can mitigate the performance impact by changing settings.

https://gyazo.com/12367b215e270e5853d0a259a56a14a9
https://gyazo.com/873c4b9194a59c0ad7aba790ec950328
https://gyazo.com/94284129bfb803e0a0ca624ad92c84c9

**Comment by umireon** [comment]
Can you disable "Skip image based on similarity" and check if the issue is mitigated?

**Comment by DJ-Iceman** [comment]
> Can you disable "Skip image based on similarity" and check if the issue is mitigated?

Negative no change

**Comment by DJ-Iceman** [comment]
It's very possible that this is a very similar issue that WaldoAndFriends reported due to a compatibility issue with the Source Clone plugin from Exeldro. #554 because i have a few Camera source clones, at any rate i will leave it with you to sort and looking forward to resolve. Keep up the great work!
