### ISSUE TITLE
Version 1.1.13 doesn't work

### ISSUE THREAD

**Issue by smnbgn** [occ-ai/obs-backgroundremoval#570]
Version 1.1.13 doesn't work on my computer, but 1.1.12 does.

The processor is AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx.

**Comment by umireon** [comment]
Please post there the OBS log and the screenshot.

**Comment by smnbgn** [comment]
Here is the log. Nothing happens in OBS, it just doesn't remove the background.
[backgroundremoveal_obs.txt](https://github.com/occ-ai/obs-backgroundremoval/files/14810882/backgroundremoveal_obs.txt)

**Comment by umireon** [comment]
OK. Then can we close this issue?

**Comment by smnbgn** [comment]
I don't think so. The setting GPU - DirectML works under version 1.1.12.

**Comment by umireon** [comment]
You are on Windows?

**Comment by smnbgn** [comment]
Windows 10, yes.

**Comment by umireon** [comment]
How do you install our plugin?

**Comment by smnbgn** [comment]
https://github.com/occ-ai/obs-backgroundremoval/releases/download/1.1.13/obs-backgroundremoval-1.1.13-windows-x64-Installer.exe

**Comment by umireon** [comment]
Unfortunately, we don't have any Windows 10 machine. Can you investigate the root cause of this error and cotribute back to our repository?

Maybe related to https://github.com/microsoft/onnxruntime/issues/19405

I think this might be an upstream issue.

**Comment by umireon** [comment]
The version of ONNX Runtime have been upgraded from 1.16.3 to 1.17.1 at obs-backgroundremoval 1.1.13.

**Comment by KenCarter01** [comment]
Same issue for me.

**Comment by umireon** [comment]
@royshil Can we close this issue as lack of information?

**Comment by umireon** [comment]
We need another person who can provide the detail of this bug.

**Comment by smnbgn** [comment]
> Unfortunately, we don't have any Windows 10 machine. Could you please investigate the root cause of this error and contribute back to our repository?

I can't even build the plugin on Windows because of outdated sources in the scripts.

**Comment by umireon** [comment]
Closing this issue as this got a catch-all issue

**Comment by umireon** [comment]
I believe our code can be built without problems on Windows and it should be a problem specific to your enivironment.
