### ISSUE TITLE
Not able to update the obs on `linux`

### ISSUE THREAD

**Issue by carrycooldude** [occ-ai/obs-backgroundremoval#573]
**Describe the bug**

![Screenshot from 2024-04-10 14-27-20](https://github.com/occ-ai/obs-backgroundremoval/assets/41143496/c9232737-85ee-44aa-81df-dc80b7a795b7)

**Log and Crash Report**

Upload your OBS log file here (`Help`>`Log Files`>`Show Log Files`) to help us find cause of the problem.

If OBS is crashing, upload the crash report here as well (`Help`>`Crash Reports`>`Show Crash Reports`).

**Desktop (please complete the following information):**

 - OS: Ubuntu 
 - Browser: Desktop

**Additional context**

**Comment by umireon** [comment]
We could not understand what you want us to help you about.
Please describe your problem in words.

**Comment by carrycooldude** [comment]
> We could not understand what you want us to help you about. Please describe your problem in words.

Basically I am not able to upgrade new version of OBS on Ubuntu
