### ISSUE TITLE
OBS does not load plugin

### ISSUE THREAD

**Issue by pedjas** [occ-ai/obs-backgroundremoval#574]
**Describe the bug**

I installed plugin using exe but OBS does not load it. It shows in log that it supposedly cannot find dll.

**To Reproduce**

OBS Studio is installed in C:\Program Files\obs-studio\

Plugin is installed using 64bit exe. 

DLL is located at C:\Program Files\obs-studio\obs-plugins\64bit\obs-backgroundremoval.dll

When OBS Studio is started it does not load plugin. Plugin does not show in Filters.

I found this in log:

14:58:08.019: LoadLibrary failed for '../../obs-plugins/64bit/obs-backgroundremoval.dll': The specified module could not be found.
14:58:08.019:  (126)
14:58:08.020: Module '../../obs-plugins/64bit/obs-backgroundremoval.dll' not loaded

**Expected behavior**

Plugin should load.

**Log and Crash Report**

14:58:08.019: LoadLibrary failed for '../../obs-plugins/64bit/obs-backgroundremoval.dll': The specified module could not be found.
14:58:08.019:  (126)
14:58:08.020: Module '../../obs-plugins/64bit/obs-backgroundremoval.dll' not loaded

OBS Studio does not crash so no Crash Report is created.

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser: Firefox
 - Plugin Version: 1.1.13 Windows x64
 - OBS Version: 30.1.2 (but did not work with some previous version too)

**Additional context**

I read that it is possible that DLL has some dependency that does not load but in plugin description there is no mention on dependencies.

**Comment by umireon** [comment]
Please provide us the full log.

**Comment by royshil** [comment]
@pedjas can you make sure the DirectML.dll file also exists in the plugins folder alongside the pluging dll?

**Comment by alexander-korotkiy** [comment]
> @pedjas can you make sure the DirectML.dll file also exists in the plugins folder alongside the pluging dll?

Have the same issue. File DirectML.dll is located in same direcoty with plugin dll file

**Comment by umireon** [comment]
@royshil Can we close this issue as stalled as the original author does not respond?

**Comment by umireon** [comment]
@alexander-korotkiy Please consider filing a new issue with your detailed description.

**Comment by royshil** [comment]
closing stale
