### ISSUE TITLE
Background color setting is missing from background removal advanced settings

### ISSUE THREAD

**Issue by 68mph** [occ-ai/obs-backgroundremoval#578]
The background color setting is missing from the Background removal settings panel.

 - OS: Sonoma 14.4.1
 - Browser: \[e.g. chrome, safari\]
 - Plugin Version:obs-backgroundremoval-1.1.13-macos-universal.pkg
 - OBS Version: 30.1.2

**Comment by umireon** [comment]
Background color option was removed a long time ago.
