### ISSUE TITLE
OBS launch error after installing plugin

### ISSUE THREAD

**Issue by Slattsveen** [occ-ai/obs-backgroundremoval#583]
**Describe the bug**

After I install the plugin, I get a warning that "OBS did not shut down properly during last session". 
I get this after installing both manually and using the installer. 

![image](https://github.com/occ-ai/obs-backgroundremoval/assets/22937548/18556e51-246e-41bb-8469-5098b1c1477a)

Are there any additional steps to the installation procedure that are not described?

**To Reproduce**

Installed latest version OBS (updated this morning), no other third party plugins installed.
![image](https://github.com/occ-ai/obs-backgroundremoval/assets/22937548/62d2ce78-c88f-464b-aaba-8c45ee39e42f)

Installed latest Background removal: 
![image](https://github.com/occ-ai/obs-backgroundremoval/assets/22937548/00cb055d-6674-49f8-bc31-06c7e90d050d)

See that I am not able to launch OBS. The second time I try to launch it, I get the warning about bad shutdown from last session (even though I closed the program using the EXIT button. 

If I delete the .dll file from obs-plugins the problem goes away.

**Expected behavior**

**Screenshots**

**Log and Crash Report**

Upload your OBS log file here (`Help`>`Log Files`>`Show Log Files`) to help us find cause of the problem.

If OBS is crashing, upload the crash report here as well (`Help`>`Crash Reports`>`Show Crash Reports`).

**Desktop (please complete the following information):**

 - OS: \[e.g. iOS\]
 - Browser: \[e.g. chrome, safari\]
 - Plugin Version: \[e.g. 0.5.1\]
 - OBS Version: \[e.g. 28.02\]

**Additional context**

Windows 11, 64bit system, updated as of today.

**Comment by Slattsveen** [comment]
Just to add, I can launch OBS in Safe-mode without issue

**Comment by umireon** [comment]
Please attatch logs. Logs available on Help menu

**Comment by valtingojer** [comment]
same issue in here
obs 30.1.2
obs-backgroundremoval-1.1.13-windows-x64
