### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by PaulDay1** [occ-ai/obs-backgroundremoval#587]
I downloaded the RAR file, 
I installed WINRar
I Ran the downloaded RAR file, 

Issue -  Window popups up - File Association Helper 
             Unable to find software to open this file
            File Name:  OBS-backgroundremoval-1.1.1.13-Macros-universal.pkg

What do you want to do?
           1. Search the web for suitable software
           2.  Learn more about the .pkg format
           3.  Search through windows

I DO NOT KNOW WHAT TO DO??????   help

**Comment by royshil** [comment]
If you're on Windows please download the .exe installers

Seems you tried to use the Macos installer? That's just for Mac

**Comment by PaulDay1** [comment]
Hello , it’s
 Paul from BizAdvisoryBoard.com, 
 
Thank you - I did not realize - I downloaded
 the exe verson and it ran
 
 
Warm Regards,
 
Paul Daigle 
CEO
 

 
Phone and WhatsApp +1-407-461-0061

***@***.***
Paul
 Daigle on LinkedIn 
BizAdvisoryBoard.com

 

 
 
Affiliations:   

============================================================================
 
Email sent to: , , ,
 ***@***.***
 
CONFIDENTIALITY
 NOTICE:This message and any attachment(s)
 are intended for the named recipients, only
 and may contain confidential, proprietary
 or legally privileged information and no
 such privilege is waived by errant transmission.
 If you receive this message in error, please
 delete it and all copies and notify the sender
 immediately. Unauthorized access, use, dissemination
 or reproduction of this message or attachments
 is prohibited and may be unlawful. OfficeByte,
 LLC, d/b/a BizAdvisoryBoard is based in the
 United States of America. Any personal data
 subject to the GDPR sent to BizAdvisoryBoard
 will be handled in accordance with applicable
 contracts and privacy policies, and use limited
 to the legitimate purposes for which the
 personal data has been given to OfficeByte,
 LLC, d/b/a BizAdvisoryBoard.

----------------------- Original
 Message -----------------------
  
From: "Roy Shilkrot" ***@***.***>
To: occ-ai/obs-backgroundremoval
 ***@***.***>
Cc: PaulDay1 ***@***.***>,
 Author ***@***.***>
Date: Fri, 14 Jun 2024 16:47:12
 -0700
Subject: Re: [occ-ai/obs-backgroundremoval]
 Install (Issue #587)
  

If you're on Windows please download the
 .exe installers
Seems you tried to use the Macos installer?
 That's just for Mac
—Reply
 to this email directly, view
 it on GitHub, or unsubscribe.You
 are receiving this because you authored the
 thread.Message ID: 
***@***.***>
