### ISSUE TITLE
Installing on Mac OS

### ISSUE THREAD

**Issue by CamilaAmore** [occ-ai/obs-backgroundremoval#588]
I do not see instructions on how to link the ops-background removal plugin to obs. I installed it from the macOS option but it does not populate into my obs filter options. Are there intermediate steps I'm missing?

**Comment by djarthurmiller** [comment]
I've having a similar issue with the plugin on OBS 29.0.2 on MacOS 10.15.7.
Strangely, there is no problem with this release on OBS 27.2.4.
Here is the relevant info from the log:
`18:26:57.804: os_dlopen(/Users/jason/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval->/Users/jason/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval): dlopen(/Users/jason/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval, 257): Library not loaded: @rpath/obs-frontend-api.dylib
18:26:57.804:   Referenced from: /Users/jason/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval
18:26:57.804:   Reason: image not found
18:26:57.804: 
18:26:57.804: Module '/Users/jason/Library/Application Support/obs-studio/plugins/obs-backgroundremoval.plugin/Contents/MacOS/obs-backgroundremoval' not loaded
`

**Comment by umireon** [comment]
@djarthurmiller 

OBS 29 and 27 are not supported now. You have our plugin working on OBS 27, but we can only guarantee that our plugin works on OBS 30. We can't say anything about 27, 28, or 29. I'd like you to upgrade your OBS installation to the latest 30.

**Comment by djarthurmiller** [comment]
Thanks for the quick reply... I can confirm the plugin works on OBS30+. (For others with this issue: Legacy machines without support for macOS 11+ are unfortunately limited to OBS 29.0.2.)
