### ISSUE TITLE
Unable to load plug-in on Linux

### ISSUE THREAD

**Issue by securitybryan** [occ-ai/obs-backgroundremoval#589]
**Describe the bug**

I installed OBS from Snap.  The version is 30.0.2.

When I start OBS it tells me that my version of obs-backgroundremoval is out of date and to install 1.1.13.

I have installed 1.1.13 but I still get that notification upon startup and obs-backgroundremoval is not in my list of filters.

Where does the plug-in install by default?  Find is not locating it.  If I know, I can copy it over to the current Snap plug-in folder for OBS.

**Desktop (please complete the following information):**

 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Plugin Version: 1.1.13
 - OBS Version: 30.0.2

**Additional context**

**Comment by umireon** [comment]
Please post the log and a screenshot that indicates that our plugin is not loaded.

**Comment by securitybryan** [comment]
I removed the Snap install and installed via flatpack.  I am testing now to see if it installed.

**Comment by securitybryan** [comment]
Here is the screenshot which indicates the plugin is not available in the video filters list.  

![image](https://github.com/occ-ai/obs-backgroundremoval/assets/57107035/d6148f6c-52e6-4a59-a3b2-1b581d645b75)

**Comment by umireon** [comment]
Please post here the image of the whole screen

**Comment by umireon** [comment]
Do you use Flatpak version or APT version?

**Comment by umireon** [comment]
You have to install Flatpak edition of our plugin with Flatpak OBS.

**Comment by securitybryan** [comment]
Hmmm....apologies.  I must have missed that in the instructions.

I will remove the plugin and re-install via Flatpak

**Comment by securitybryan** [comment]
Installing both OBS and the plugin using Flatpak solved the issue.  Thank you for the quick response.
